const TEXT = {
  en: {
    status: "Status",
    applicationType: "Application Type",
    prepareCase: "Prepare Case",
    applicationForSite: "Application for Site (New Site)",
    applicationTypeOpenSpace: "Open Space",
    applicationTypeBuilding: "Building",
    applicationOfSitingProject: "Application of Siting Project",
    digitalReference: "Digital Reference",
    agencyReference: "Agency Reference",
    division: "Division",
    back: "Back",
    backToDashboard: "Back to Dashboard",
    backToAwaitingApproval: "Back to Awaiting Approval",
    backToActionPanel: "Back to Action Panel",
    previous: "Previous",
    next: "Next",
    saveNext: "Save & Next",
    saveDraftBackApplications: "Save Draft & Back to Applications",
    draftSavedWithoutUpload: "Draft saved, but the site image could not be uploaded. Please upload it again when you continue the draft.",
    saving: "Saving...",
    submitting: "Submitting...",
    saveSubmit: "Save & Submit Application",
    requiredAlert: "Please fill in all required fields before proceeding to the next step.",
    missingApplication: "Application ID is missing. Please continue from My Dashboard.",
    draftConfirm: "You have unsaved changes. Save this application as draft before leaving?",
    failedSaveStep1: "Failed to save Step 1. Please try again.",
    failedSaveStep2: "Failed to save Step 2.",
    failedSaveDraft: "Failed to save draft.",
    failedSaveDeclaration: "Failed to save declaration.",
    failedUpload: "Failed to upload file.",
    failedDownload: "Failed to download file.",
    readOnlyPrefix: "This application is",
    readOnlySuffix: "and can only be viewed.",
    readOnlyCorrection: "If it is rejected with remarks, use Edit from the applications list to make corrections.",
    sittingApplication: "Sitting Application",
    typeOfApplication: "Type of Application",
    nameOfProject: "Name of Project",
    applicant: "Applicant",
    contactPerson: "Contact Person",
    telNo: "Tel No.",
    localityAddress: "Locality / Address",
    locationMap: "Location Map",
    projectAddressSearch: "Project Address / Location Search (Selected Address)",
    addressSearchPlaceholder: "Search building name, road, lot number or landmark in Malaysia...",
    searchingAddress: "Searching address...",
    addressSearchHelp: "Search by building name, road, lot number or landmark across Malaysia. The selected result will be used as the project address. You may also drag the pin or click the map to update the address automatically.",
    pinpointLocation: "Pinpoint Project Location",
    pinpointHelp: "Drag the red pin or click the map to update address, latitude, and longitude.",
    focus: "Focus",
    flyBackTitle: "Fly back to pinned location",
    street: "Street",
    satellite: "Satellite",
    outdoor: "Outdoor",
    latitude: "Latitude",
    longitude: "Longitude",
    updatingAddress: "Updating address...",
    siteImage: "Site Image",
    clickUploadSiteImage: "Click to upload site image",
    imageOnly: "JPG / PNG only",
    remove: "Remove",
    replace: "Replace",
    siteImageHelp: "Upload actual site photo for verification. This helps officer validate location and condition of the site.",
    areaRequired: "Area Required",
    totalSchemeValue: "Total Scheme Value, RM",
    totalSchemeValuePlaceholder: "Total Scheme Value",
    fundApprovedIn: "Amount of fund approved in the",
    fundApprovedMalaysiaPlan: "Amount of Fund Approved in the Malaysia Plan, RM",
    malaysiaPlan: "Malaysia Plan",
    malaysiaPlanRm: "Malaysia Plan, RM",
    fundAvailableNow: "Amount of fund available now, RM",
    fundAvailableNowTitle: "Amount of Fund Available Now, RM",
    sourceOfFund: "Source of Fund",
    fundAvailability: "Fund Availability",
    projectJustification: "Project Justification and Description on Project Components",
    projectBriefHelp: "Project brief to be submitted, together with conceptual site layout plan if available; additional sheet to be attached if insufficient space.",
    siteSelectionReason: "Reason for Selecting the Site",
    additionalSheetHelp: "Additional sheet to be attached if insufficient space.",
    designation: "Designation",
    officerName: "Name of Officer",
    date: "Date",
    draftSittingApplication: "Draft Sitting Application",
    detailsSubmittingPerson: "Details of Submitting Person",
    organisation: "Organisation",
    organisationType: "Organisation Type",
    registrationNumber: "Registration Number (if applicable)",
    name: "Name",
    branchName: "Branch Name",
    postalAddress: "Postal Address",
    postcode: "Postcode",
    address2: "Address 2",
    address3: "Address 3",
    address4: "Address 4",
    state: "State",
    city: "City",
    countryCode: "Country Code",
    telephoneNo: "Telephone No",
    submittingPerson: "Submitting Person",
    honoraryTitle: "Honorary Title",
    fullName: "Full Name",
    identityCardNo: "Identity Card No",
    officeNo: "Telephone No (Office)",
    mobileNo: "Telephone No (Mobile)",
    faxNo: "Telephone No (Fax)",
    faxPlaceholder: "Fax Number",
    email: "Email",
    pleaseSelect: "-- Please Select --",
    select: "-- Select --",
    selectState: "-- Select State --",
    selectCity: "-- Select City --",
    selectStateFirst: "-- Select State First --",
    selectTitle: "-- Select Title --",
    localAuthority: "Local Authority",
    company: "Company",
    governmentAgency: "Government Agency",
    individual: "Individual",
    supportingDocument: "Supporting Document",
    requiredSupportingDocuments: "Required Supporting Documents",
    title: "Title",
    description: "Description",
    format: "Format",
    attachment: "Attachment",
    action: "Action",
    guidelines: "Guidelines",
    noAttachment: "No attachment found.",
    extractTitles: "Extract of Document of Titles of the Land",
    landInformation: "Land Information",
    noLandInfo: "No land information found from Step 1.",
    otherSupportingDocuments: "Other Relevant Supporting Documents (If Any)",
    addDocument: "+ Add Document",
    noRecord: "--No record--",
    documentDescriptionPlaceholder: "Enter document description",
    deleteRow: "Delete Row",
    upload: "Upload",
    download: "Download",
    removeFile: "Remove file",
    missingDocumentsPrefix: "Please upload all required supporting documents before continuing:",
    failedSaveSupporting: "Failed to save Supporting Document.",
    failedSavePrint: "Failed to save Print Form.",
    declaration: "Declaration",
    confirmDeclaration: "Please confirm the declaration before proceeding.",
    printForm: "Print Form",
    reviewGeneratedForm: "Review the generated application form below. Click Download PDF to download the PDF.",
    printSavePdf: "Download PDF",
    generatedFormTitle: "SITING APPLICATION FORM",
    step1Print: "Step 1: Sitting Application",
    step2Print: "Step 2: Details of Submitting Person",
    step3Print: "Step 3: Supporting Documents",
    organisationName: "Organisation Name",
    cityState: "City / State",
  },
  ms: {
    status: "Status",
    applicationType: "Jenis Permohonan",
    prepareCase: "Sedia Kes",
    applicationForSite: "Permohonan Tapak (Tapak Baharu)",
    applicationTypeOpenSpace: "Kawasan Lapang",
    applicationTypeBuilding: "Bangunan",
    applicationOfSitingProject: "Permohonan Projek Penempatan",
    digitalReference: "Rujukan Digital",
    agencyReference: "Rujukan Agensi",
    division: "Bahagian",
    back: "Kembali",
    backToDashboard: "Kembali ke Papan Pemuka",
    backToAwaitingApproval: "Kembali ke Menunggu Kelulusan",
    backToActionPanel: "Kembali ke Panel Tindakan",
    previous: "Sebelumnya",
    next: "Seterusnya",
    saveNext: "Simpan & Seterusnya",
    saveDraftBackApplications: "Simpan Draf & Kembali ke Permohonan",
    draftSavedWithoutUpload: "Draf disimpan, tetapi imej tapak tidak dapat dimuat naik. Sila muat naik semula apabila menyambung draf.",
    saving: "Menyimpan...",
    submitting: "Menghantar...",
    saveSubmit: "Simpan & Hantar Permohonan",
    requiredAlert: "Sila lengkapkan semua medan wajib sebelum meneruskan ke langkah seterusnya.",
    missingApplication: "ID permohonan tiada. Sila teruskan dari Papan Pemuka Saya.",
    draftConfirm: "Anda mempunyai perubahan yang belum disimpan. Simpan permohonan ini sebagai draf sebelum keluar?",
    failedSaveStep1: "Gagal menyimpan Langkah 1. Sila cuba lagi.",
    failedSaveStep2: "Gagal menyimpan Langkah 2.",
    failedSaveDraft: "Gagal menyimpan draf.",
    failedSaveDeclaration: "Gagal menyimpan akuan.",
    failedUpload: "Gagal memuat naik fail.",
    failedDownload: "Gagal memuat turun fail.",
    readOnlyPrefix: "Permohonan ini berada pada status",
    readOnlySuffix: "dan hanya boleh dilihat.",
    readOnlyCorrection: "Jika ditolak dengan catatan, gunakan Sunting daripada senarai permohonan untuk membuat pembetulan.",
    sittingApplication: "Permohonan Tapak",
    typeOfApplication: "Jenis Permohonan",
    nameOfProject: "Nama Projek",
    applicant: "Pemohon",
    contactPerson: "Orang Untuk Dihubungi",
    telNo: "No. Telefon",
    localityAddress: "Lokaliti / Alamat",
    locationMap: "Peta Lokasi",
    projectAddressSearch: "Carian Alamat / Lokasi Projek (Alamat Dipilih)",
    addressSearchPlaceholder: "Cari nama bangunan, jalan, nombor lot atau mercu tanda di Malaysia...",
    searchingAddress: "Mencari alamat...",
    addressSearchHelp: "Cari mengikut nama bangunan, jalan, nombor lot atau mercu tanda di seluruh Malaysia. Keputusan yang dipilih akan digunakan sebagai alamat projek. Anda juga boleh menyeret pin atau klik pada peta untuk mengemas kini alamat secara automatik.",
    pinpointLocation: "Tentukan Lokasi Projek",
    pinpointHelp: "Seret pin merah atau klik peta untuk mengemas kini alamat, latitud dan longitud.",
    focus: "Fokus",
    flyBackTitle: "Kembali ke lokasi pin",
    street: "Jalan",
    satellite: "Satelit",
    outdoor: "Luar",
    latitude: "Latitud",
    longitude: "Longitud",
    updatingAddress: "Mengemas kini alamat...",
    siteImage: "Imej Tapak",
    clickUploadSiteImage: "Klik untuk muat naik imej tapak",
    imageOnly: "JPG / PNG sahaja",
    remove: "Buang",
    replace: "Ganti",
    siteImageHelp: "Muat naik gambar tapak sebenar untuk pengesahan. Ini membantu pegawai mengesahkan lokasi dan keadaan tapak.",
    areaRequired: "Keluasan Diperlukan",
    totalSchemeValue: "Jumlah Nilai Skim, RM",
    totalSchemeValuePlaceholder: "Jumlah Nilai Skim",
    fundApprovedIn: "Jumlah dana diluluskan dalam",
    fundApprovedMalaysiaPlan: "Jumlah Dana Diluluskan dalam Rancangan Malaysia, RM",
    malaysiaPlan: "Rancangan Malaysia",
    malaysiaPlanRm: "Rancangan Malaysia, RM",
    fundAvailableNow: "Jumlah dana tersedia sekarang, RM",
    fundAvailableNowTitle: "Jumlah Dana Tersedia Sekarang, RM",
    sourceOfFund: "Sumber Dana",
    fundAvailability: "Ketersediaan Dana",
    projectJustification: "Justifikasi Projek dan Penerangan Komponen Projek",
    projectBriefHelp: "Ringkasan projek perlu dikemukakan bersama pelan susun atur tapak konsep jika ada; helaian tambahan hendaklah dilampirkan jika ruang tidak mencukupi.",
    siteSelectionReason: "Sebab Pemilihan Tapak",
    additionalSheetHelp: "Helaian tambahan hendaklah dilampirkan jika ruang tidak mencukupi.",
    designation: "Jawatan",
    officerName: "Nama Pegawai",
    date: "Tarikh",
    draftSittingApplication: "Draf Permohonan Tapak",
    detailsSubmittingPerson: "Butiran Orang Yang Mengemukakan",
    organisation: "Organisasi",
    organisationType: "Jenis Organisasi",
    registrationNumber: "Nombor Pendaftaran (jika berkenaan)",
    name: "Nama",
    branchName: "Nama Cawangan",
    postalAddress: "Alamat Surat-Menyurat",
    postcode: "Poskod",
    address2: "Alamat 2",
    address3: "Alamat 3",
    address4: "Alamat 4",
    state: "Negeri",
    city: "Bandar",
    countryCode: "Kod Negara",
    telephoneNo: "No. Telefon",
    submittingPerson: "Orang Yang Mengemukakan",
    honoraryTitle: "Gelaran Kehormat",
    fullName: "Nama Penuh",
    identityCardNo: "No. Kad Pengenalan",
    officeNo: "No. Telefon (Pejabat)",
    mobileNo: "No. Telefon (Bimbit)",
    faxNo: "No. Telefon (Faks)",
    faxPlaceholder: "Nombor Faks",
    email: "E-mel",
    pleaseSelect: "-- Sila Pilih --",
    select: "-- Pilih --",
    selectState: "-- Pilih Negeri --",
    selectCity: "-- Pilih Bandar --",
    selectStateFirst: "-- Pilih Negeri Dahulu --",
    selectTitle: "-- Pilih Gelaran --",
    localAuthority: "Pihak Berkuasa Tempatan",
    company: "Syarikat",
    governmentAgency: "Agensi Kerajaan",
    individual: "Individu",
    supportingDocument: "Dokumen Sokongan",
    requiredSupportingDocuments: "Dokumen Sokongan Wajib",
    title: "Tajuk",
    description: "Penerangan",
    format: "Format",
    attachment: "Lampiran",
    action: "Tindakan",
    guidelines: "Garis Panduan",
    noAttachment: "Tiada lampiran dijumpai.",
    extractTitles: "Cabutan Dokumen Hakmilik Tanah",
    landInformation: "Maklumat Tanah",
    noLandInfo: "Tiada maklumat tanah dijumpai daripada Langkah 1.",
    otherSupportingDocuments: "Dokumen Sokongan Berkaitan Lain (Jika Ada)",
    addDocument: "+ Tambah Dokumen",
    noRecord: "--Tiada rekod--",
    documentDescriptionPlaceholder: "Masukkan penerangan dokumen",
    deleteRow: "Padam Baris",
    upload: "Muat Naik",
    download: "Muat Turun",
    removeFile: "Buang fail",
    missingDocumentsPrefix: "Sila muat naik semua dokumen sokongan wajib sebelum meneruskan:",
    failedSaveSupporting: "Gagal menyimpan Dokumen Sokongan.",
    failedSavePrint: "Gagal menyimpan Cetak Borang.",
    declaration: "Akuan",
    confirmDeclaration: "Sila sahkan akuan sebelum meneruskan.",
    printForm: "Cetak Borang",
    reviewGeneratedForm: "Semak borang permohonan yang dijana di bawah. Klik Muat Turun PDF untuk memuat turun PDF.",
    printSavePdf: "Muat Turun PDF",
    generatedFormTitle: "BORANG PERMOHONAN PENEMPATAN",
    step1Print: "Langkah 1: Permohonan Tapak",
    step2Print: "Langkah 2: Butiran Orang Yang Mengemukakan",
    step3Print: "Langkah 3: Dokumen Sokongan",
    organisationName: "Nama Organisasi",
    cityState: "Bandar / Negeri",
  },
};

const DOCUMENT_TEXT = {
  "Site Plan": {
    title: { en: "Site Plan", ms: "Pelan Tapak" },
    description: {
      en: "To be drawn on Cadastral Plan showing the subject land and the surrounding land (preferred scale 1:1000) involving:-\nSite; or\nbuilding plan.\nIf none of above, drawing on Google Map is accepted.",
      ms: "Hendaklah dilukis pada Pelan Kadaster yang menunjukkan tanah berkaitan dan tanah sekeliling (skala pilihan 1:1000) melibatkan:-\nTapak; atau\npelan bangunan.\nJika tiada, lukisan pada Google Map diterima.",
    },
  },
  "Cadastral Plan": {
    title: { en: "Cadastral Plan", ms: "Pelan Kadaster" },
    description: {
      en: "Cadastral plan (preferred scale 1:1000) showing the subject land and the surrounding land.\nDigital copy is available from eLASIS website.",
      ms: "Pelan kadaster (skala pilihan 1:1000) yang menunjukkan tanah berkaitan dan tanah sekeliling.\nSalinan digital boleh didapati daripada laman web eLASIS.",
    },
  },
  "Site Photographs": {
    title: { en: "Site Photographs", ms: "Gambar Tapak" },
    description: { en: "-", ms: "-" },
  },
  "Tenancy Agreement": {
    title: { en: "Tenancy Agreement", ms: "Perjanjian Sewaan" },
    description: { en: "-", ms: "-" },
  },
  "Extract of Document of Titles of the Land": {
    title: { en: "Extract of Document of Titles of the Land", ms: "Cabutan Dokumen Hakmilik Tanah" },
  },
  "Other Relevant Supporting Documents (If Any)": {
    title: {
      en: "Other Relevant Supporting Documents (If Any)",
      ms: "Dokumen Sokongan Berkaitan Lain (Jika Ada)",
    },
  },
};

const STATUS_TEXT = {
  "prepare case": { en: "Prepare Case", ms: "Sedia Kes" },
  draft: { en: "Draft", ms: "Draf" },
  saved: { en: "Saved", ms: "Disimpan" },
  submitted: { en: "Submitted", ms: "Dihantar" },
  "under review": { en: "Under Review", ms: "Dalam Semakan" },
  generated: { en: "Generated", ms: "Dijana" },
  incomplete: { en: "Incomplete", ms: "Tidak Lengkap" },
  rejected: { en: "Rejected", ms: "Ditolak" },
  approved: { en: "Approved", ms: "Diluluskan" },
  "approved with conditions": { en: "Approved with Conditions", ms: "Lulus Bersyarat" },
  "s2 verification": { en: "S2 Verification", ms: "Verifikasi S2" },
  "technical review": { en: "Technical Review", ms: "Semakan Teknikal" },
  "technical site visit": { en: "Technical Site Visit", ms: "Lawatan Tapak Teknikal" },
  "technical amendment required": { en: "Technical Amendment Required", ms: "Pindaan Teknikal Diperlukan" },
  "technical completed": { en: "Technical Completed", ms: "Teknikal Selesai" },
  "management recommendation": { en: "Management Recommendation", ms: "Perakuan Pengurusan" },
  "mphlg processing": { en: "MPHLG Processing", ms: "Proses MPHLG" },
  "mphlg decision received": { en: "MPHLG Decision Received", ms: "Keputusan MPHLG Diterima" },
  "invoice generated": { en: "Invoice Generated", ms: "Invois Dijana" },
  "payment submitted": { en: "Payment Submitted", ms: "Bayaran Dihantar" },
  "payment verified": { en: "Payment Verified", ms: "Bayaran Disahkan" },
  "e-license generated": { en: "E-License Generated", ms: "E-Lesen Dijana" },
  "license revoked": { en: "License Revoked", ms: "Lesen Dibatalkan" },
};

export function stepText(language, key) {
  const locale = language === "ms" ? "ms" : "en";
  return TEXT[locale][key] || TEXT.en[key] || key;
}

export function documentTitle(language, title) {
  const locale = language === "ms" ? "ms" : "en";
  return DOCUMENT_TEXT[title]?.title?.[locale] || title;
}

export function documentDescription(language, title, description) {
  const locale = language === "ms" ? "ms" : "en";
  return DOCUMENT_TEXT[title]?.description?.[locale] || description;
}

export function applicationStatusLabel(language, status) {
  const locale = language === "ms" ? "ms" : "en";
  const key = String(status || "").trim().toLowerCase();
  return STATUS_TEXT[key]?.[locale] || status || stepText(language, "prepareCase");
}

export function applicationTypeLabel(language, type) {
  const text = String(type || "");

  if (text.includes("New Site")) {
    return stepText(language, "applicationForSite");
  }

  if (text.includes("Siting Project")) {
    return stepText(language, "applicationOfSitingProject");
  }

  return text || stepText(language, "applicationForSite");
}

export function organisationTypeLabel(language, type) {
  const labels = {
    "Local Authority": "localAuthority",
    Company: "company",
    "Government Agency": "governmentAgency",
    Individual: "individual",
  };

  return labels[type] ? stepText(language, labels[type]) : type || "-";
}

export function readOnlyMessage(language, statusLabel) {
  return `${stepText(language, "readOnlyPrefix")} ${String(statusLabel || "").toLowerCase()} ${stepText(language, "readOnlySuffix")} ${stepText(language, "readOnlyCorrection")}`;
}
