/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "fastrack_language";

const adminWorkflowMs = {
  "admin.dashboard.eyebrow": "Papan Pemuka Pentadbir",
  "admin.dashboard.title": "Senarai Tugasan",
  "admin.dashboard.description": "Tugasan akan muncul selepas pemohon menghantar permohonan. PT(IKL), KU(IKL), unit teknikal, KB(LES), TP/PGH dan MPHLG boleh menyemak, menolak dengan catatan, atau meneruskan permohonan mengikut aliran kerja.",
  "admin.dashboard.submittedForms": "Borang Dihantar",
  "admin.dashboard.taskToClaim": "Tugasan Untuk Dituntut",
  "admin.dashboard.units": "Unit",
  "admin.dashboard.application": "Permohonan",
  "admin.dashboard.personalTask": "Tugasan Peribadi",
  "admin.dashboard.claimableTask": "Senarai Tugasan Untuk Dituntut",
  "admin.dashboard.allClaimedTask": "Senarai Semua Tugasan Dituntut",
  "admin.dashboard.awaitingApproval": "Menunggu Kelulusan",
  "admin.dashboard.licenseCode": "Lesen / Kod",
  "admin.dashboard.processList": "SENARAI PROSES",
  "admin.dashboard.taskCount": "Bilangan Tugasan",
  "admin.dashboard.administrator": "Pentadbir",
  "admin.dashboard.dataEntry": "(Kemasukan Data)",
  "admin.dashboard.welcome": "Selamat datang",
  "admin.dashboard.taskQueue": "Giliran Tugasan",
  "admin.dashboard.roleTitle": "Peranan Tugasan",
  "admin.dashboard.ptIklRole": "PT(IKL): Semak maklumat dan dokumen pemohon. Tolak kepada pemohon bersama catatan jika tidak lengkap.",
  "admin.dashboard.kuIklRole": "KU(IKL): Sahkan semakan kedua, tolak jika perlu pindaan, atau hantar kepada teknikal.",
  "admin.dashboard.unitIklanTechnicalRole": "Unit Iklan Teknikal (PT/PO/KP): Buat lawatan tapak, muat naik gambar, kira caj lesen/deposit dan rekod catatan tapak.",
  "admin.dashboard.openWorkspace": "Buka Ruang Kerja Unit",
  "admin.dashboard.queueDescription": "Permohonan yang sedang menunggu tindakan unit ini.",
  "admin.dashboard.noTask": "Tiada tugasan untuk unit ini.",
  "admin.unit.ikl.desc": "PT(IKL) menyemak kelengkapan, menolak dengan catatan jika perlu, KU(IKL) mengesahkan semakan kedua dan menyerahkan kepada teknikal.",
  "admin.unit.blg.desc": "BLG menjalankan lawatan tapak dan memberi keputusan sokong, sokongan bersyarat atau tidak disokong bersama catatan.",
  "admin.unit.imt.desc": "IMT menyemak infrastruktur dan integrasi lokasi iklan serta memberi keputusan teknikal.",
  "admin.unit.mne.desc": "MNE menyemak aspek mekanikal dan elektrikal di lokasi iklan serta memberi keputusan teknikal.",
  "admin.unit.eng.desc": "ENG menyemak aspek kejuruteraan dan keselamatan struktur iklan.",
  "admin.unit.gpm.desc": "GPM menyemak geoinformasi, penguasaan hartanah dan kesesuaian lokasi.",
  "admin.unit.lnp.desc": "LNP menyemak kesan landskap dan persekitaran lokasi iklan.",
  "admin.workflow.title": "Aliran Operasi Lesen Iklan",
  "admin.workflow.description": "Ringkasan aliran kerja selepas pemohon menghantar permohonan.",
  "admin.workflow.screening": "Semakan PT(IKL) dan KU(IKL)",
  "admin.workflow.screeningDesc": "PT(IKL) menyemak maklumat dan dokumen. Jika tidak lengkap, permohonan ditolak kepada pemohon bersama catatan. Jika lengkap, KU(IKL) mengesahkan sebelum dihantar kepada unit teknikal.",
  "admin.workflow.technical": "Lawatan dan Semakan Teknikal",
  "admin.workflow.technicalDesc": "Unit Iklan teknikal memuat naik gambar tapak, caj lesen/deposit dan catatan. BLG, GPM, MNE, IMT, LNP dan ENG memberi keputusan sokong, sokongan bersyarat atau tidak disokong.",
  "admin.workflow.management": "Semakan KB(LES), TP/PGH dan MPHLG",
  "admin.workflow.managementDesc": "KU(IKL) menyemak laporan teknikal, KB(LES) membuat verifikasi, TP/PGH menyokong, dan MPHLG/SUT memberi keputusan.",
  "admin.workflow.payment": "Kelulusan, Bil, Bayaran dan Lesen QR",
  "admin.workflow.paymentDesc": "PT(IKL) menjana surat dan bil, KU(IKL) mengesahkan bil, pemohon membayar dan memuat naik bukti, kemudian PT(IKL) menjana e-lesen QR.",
  "admin.workflow.renewal": "Peringatan Pembaharuan Lesen",
  "admin.workflow.renewalDesc": "Sistem mengeluarkan peringatan 3, 2 dan 1 bulan sebelum tamat tempoh. Jika tiada pembaharuan, surat pembatalan dan tindakan penguatkuasaan disediakan.",
  "workspace.screening.eyebrow": "Verifikasi PT(IKL) / KU(IKL)",
  "workspace.screening.title": "Semakan Permohonan",
  "workspace.screening.description": "Semak maklumat dan dokumen pemohon. Tolak dengan catatan jika tidak lengkap, atau serahkan kepada KU(IKL)/teknikal jika lengkap.",
  "workspace.screening.queue": "Giliran Semakan",
  "workspace.screening.action": "Rekod keputusan PT(IKL) atau KU(IKL) untuk permohonan dipilih.",
  "workspace.technical.eyebrow": "Lawatan Tapak Teknikal",
  "workspace.technical.title": "Semakan Teknikal",
  "workspace.technical.description": "Rekod keputusan bahagian dan catatan lawatan tapak untuk semakan IKL.",
  "workspace.technical.queue": "Giliran Teknikal",
  "workspace.technical.action": "Masukkan keputusan bahagian dan catatan penemuan tapak.",
  "workspace.approval.eyebrow": "KB(LES), TP/PGH dan MPHLG",
  "workspace.approval.title": "Verifikasi dan Kelulusan",
  "workspace.approval.description": "Rekod verifikasi KB(LES), sokongan TP/PGH, semakan MPHLG/SUT dan keputusan akhir.",
  "workspace.approval.queue": "Giliran Kelulusan",
  "workspace.approval.action": "Hantar keputusan atau catatan kelulusan.",
  "workspace.payment.eyebrow": "Bil dan Bayaran",
  "workspace.payment.title": "Bil, Bukti Bayaran dan Pengesahan",
  "workspace.payment.description": "Jana bil dan sahkan bukti resit bayaran yang dimuat naik.",
  "workspace.payment.queue": "Giliran Bayaran",
  "workspace.payment.action": "Jana bil, kemudian sahkan sama ada resit yang dimuat naik sah atau palsu.",
  "workspace.license.eyebrow": "E-Lesen QR dan Pembaharuan",
  "workspace.license.title": "Lesen QR dan Peringatan Pembaharuan",
  "workspace.license.description": "Jana e-lesen QR, pantau tamat tempoh dan keluarkan peringatan pembaharuan lesen.",
  "workspace.license.queue": "Giliran Lesen",
  "workspace.license.action": "Jana, batal atau pantau lesen digital.",
  "workspace.queue.instructions": "Pilih rekod, kemudian lengkapkan panel tindakan.",
  "workspace.search.placeholder": "Cari rujukan, pemohon, projek, jenis, atau lokasi",
  "workspace.empty": "Tiada permohonan dijumpai.",
  "workspace.actionPanel": "Panel Tindakan",
  "workspace.selectApplication": "Pilih permohonan.",
  "workspace.openForm": "Lihat Borang",
  "workspace.backToDashboard": "Kembali ke Papan Pemuka",
  "workspace.saving": "Menyimpan...",
  "workspace.selectedRecord": "Rekod Dipilih",
  "workspace.selectedRecordDesc": "Maklumat utama daripada rekod permohonan backend.",
  "workspace.selectedApplication": "Permohonan Dipilih",
  "workspace.defaultApplicationTitle": "Permohonan Lesen Iklan",
  "application.type.siteNew": "Permohonan Tapak (Tapak Baharu)",
  "application.type.site": "Permohonan Tapak",
  "application.type.sitting": "Permohonan Tapak",
  "application.type.signboard": "Lesen Papan Tanda",
  "application.type.buildingPlan": "Pelan Bangunan",
  "workspace.created": "Dicipta",
  "workspace.step": "Langkah",
  "workspace.location": "Lokasi",
  "workspace.decision.completeToKu": "PT(IKL) Hantar kepada KU(IKL)",
  "workspace.decision.kuToTechnical": "KU(IKL) Sahkan - Hantar kepada Unit Teknikal",
  "workspace.decision.rejectApplicant": "PT(IKL) Tolak kepada Pemohon",
  "workspace.decision.kuRejectApplicant": "KU(IKL) Tolak kepada Pemohon",
  "workspace.decision.technicalAmendment": "Pindaan Teknikal Diperlukan",
  "workspace.decision.supported": "Disokong",
  "workspace.decision.supportedConditions": "Sokongan Bersyarat",
  "workspace.decision.notSupported": "Tidak Disokong",
  "workspace.decision.kuConfirmToKb": "KU(IKL) Sahkan - Hantar kepada KB(LES)",
  "workspace.decision.kuRequestTechnicalAmendment": "KU(IKL) Minta Pindaan Teknikal",
  "workspace.decision.requiresAmendment": "Perlu Pindaan",
  "workspace.decision.approved": "Diluluskan",
  "workspace.decision.approvedConditions": "Diluluskan Dengan Syarat",
  "workspace.decision.rejected": "Ditolak",
  "workspace.comment.remarks": "Catatan",
  "workspace.comment.screeningPlaceholder": "Masukkan catatan PT(IKL) / KU(IKL). Wajib jika menolak.",
  "workspace.ikl.screeningTitle": "Verifikasi PT(IKL) / KU(IKL)",
  "workspace.ikl.screeningDesc": "Gunakan bahagian ini untuk hantar kepada KU(IKL), hantar kepada teknikal, atau tolak kepada pemohon bersama catatan.",
  "workspace.comment.technical": "Catatan",
  "workspace.comment.technicalPlaceholder": "Tambah komen bahagian, syarat, catatan tapak, atau sebab penolakan.",
  "workspace.technical.siteVisitTitle": "Lawatan Tapak Unit Iklan",
  "workspace.technical.siteVisitDesc": "Rekod fungsi PT/PO/KP: gambar tapak, kiraan caj yuran lesen iklan, deposit dan catatan penemuan.",
  "workspace.technical.sitePhoto": "Gambar Tapak",
  "workspace.technical.uploadSitePhoto": "Muat Naik Gambar Tapak",
  "workspace.technical.sitePhotoUploaded": "Gambar tapak dimuat naik",
  "workspace.technical.licenseFee": "Kiraan Caj Yuran Lesen Iklan (RM)",
  "workspace.technical.deposit": "Kiraan Deposit (RM)",
  "workspace.technical.siteRemarks": "Catatan Penemuan Tapak",
  "workspace.technical.siteRemarksPlaceholder": "Masukkan catatan lawatan tapak, isu lokasi, syarat atau penemuan lain.",
  "workspace.technical.awaitingDepartmentReviews": "Lengkapkan maklum balas BLG, GPM, MNE, IMT, LNP dan ENG sebelum keputusan akhir teknikal dibuat.",
  "workspace.technical.kuReviewTitle": "Semakan KU(IKL)",
  "workspace.technical.kuReviewDesc": "Semak keputusan akhir teknikal, caj lesen, deposit dan catatan sebelum minta pindaan atau hantar kepada KB(LES).",
  "workspace.technical.kuReviewPlaceholder": "Masukkan catatan KU(IKL), sebab pindaan atau arahan untuk semakan lanjut.",
  "workspace.technical.compiledRemarksTitle": "Catatan Bahagian Teknikal",
  "workspace.technical.compiledRemarksDesc": "Maklum balas BLG, GPM, MNE, IMT, LNP dan ENG dikemaskini untuk semakan IKL.",
  "workspace.comment.approval": "Catatan Kelulusan",
  "workspace.comment.payment": "Catatan Pengesahan Resit",
  "workspace.comment.paymentPlaceholder": "Masukkan catatan pengesahan, isu resit, atau sebab penolakan.",
  "workspace.action.submitScreening": "Hantar Keputusan PT/KU",
  "workspace.action.submitKuTechnicalReview": "Hantar Semakan KU(IKL)",
  "workspace.action.submitReview": "Hantar Semakan",
  "workspace.action.submitSiteVisit": "Hantar Lawatan Tapak",
  "workspace.action.submitDecision": "Hantar Keputusan",
  "workspace.action.generateInvoice": "Jana Bil",
  "workspace.action.submitPayment": "Hantar Bayaran",
  "workspace.action.verifyPayment": "Sahkan Resit",
  "workspace.action.rejectReceipt": "Tolak Resit",
  "workspace.action.issueLicense": "Jana Lesen",
  "workspace.action.revoke": "Batalkan",
  "workspace.message.screeningSaved": "Keputusan semakan disimpan.",
  "workspace.message.technicalSaved": "Semakan teknikal disimpan.",
  "workspace.message.kuTechnicalReviewSaved": "Semakan KU(IKL) disimpan.",
  "workspace.message.siteVisitSaved": "Lawatan tapak disimpan.",
  "workspace.message.decisionSaved": "Keputusan akhir disimpan.",
  "workspace.message.invoiceGenerated": "Bil dijana.",
  "workspace.message.paymentRecorded": "Hantaran bayaran direkodkan.",
  "workspace.message.paymentVerified": "Bayaran disahkan.",
  "workspace.message.receiptRejected": "Resit ditolak. Pemohon boleh memuat naik resit baharu.",
  "workspace.message.licenseIssued": "E-lesen dijana.",
  "workspace.message.licenseRevoked": "Lesen dibatalkan.",
  "workspace.stat.total": "Jumlah",
  "workspace.stat.pending": "Belum Selesai",
  "workspace.stat.screened": "Telah Disemak",
  "workspace.stat.passed": "Lulus",
  "workspace.stat.completed": "Selesai",
  "workspace.stat.supported": "Disokong",
  "workspace.stat.notSupported": "Tidak Disokong",
  "workspace.stat.awaiting": "Menunggu",
  "workspace.stat.approved": "Diluluskan",
  "workspace.stat.conditional": "Bersyarat",
  "workspace.stat.rejected": "Ditolak",
  "workspace.stat.invoiced": "Telah Dibil",
  "workspace.stat.submitted": "Dihantar",
  "workspace.stat.verified": "Disahkan",
  "workspace.stat.issued": "Dijana",
  "workspace.stat.revoked": "Dibatalkan",
  "workspace.stat.active": "Aktif",
  "workspace.check.applicationForm": "Borang permohonan",
  "workspace.check.location": "GIS / lokasi",
  "workspace.check.supportingDocuments": "Dokumen sokongan",
  "workspace.check.blacklist": "Semakan senarai hitam",
  "workspace.check.duplicateLocation": "Semakan lokasi pendua",
  "workspace.check.declaration": "Akuan pemohon",
  "workspace.check.passed": "Lulus",
  "workspace.check.failed": "Gagal",
  "workspace.check.warning": "Amaran",
  "workspace.info.licenseId": "ID Lesen",
  "workspace.info.expiry": "Tamat Tempoh",
  "workspace.info.verificationUrl": "URL Pengesahan",
  "workspace.info.receipt": "Resit",
  "workspace.info.viewReceipt": "Lihat resit",
  "workspace.info.verificationResult": "Keputusan Pengesahan",
  "workspace.info.verificationNotes": "Catatan Pengesahan",
  "workspace.info.notGenerated": "Belum dijana",
  "workspace.info.notSubmitted": "Belum dihantar",
  "workspace.info.pendingIssuance": "Menunggu penjanaan",
};

const adminWorkflowEn = {
  "admin.dashboard.eyebrow": "Admin Dashboard",
  "admin.dashboard.title": "List of Tasks",
  "admin.dashboard.description": "Tasks appear after an applicant submits an application. PT(IKL), KU(IKL), technical units, KB(LES), TP/PGH, and MPHLG can review, reject with remarks, or move the application through the workflow.",
  "admin.dashboard.submittedForms": "Submitted Forms",
  "admin.dashboard.taskToClaim": "Task to be Claimed",
  "admin.dashboard.units": "Units",
  "admin.dashboard.application": "Application",
  "admin.dashboard.personalTask": "Personal Task",
  "admin.dashboard.claimableTask": "List of Task to be Claimed",
  "admin.dashboard.allClaimedTask": "List of All Claimed Task",
  "admin.dashboard.awaitingApproval": "Awaiting Approval",
  "admin.dashboard.licenseCode": "License / Code",
  "admin.dashboard.processList": "PROCESS LIST",
  "admin.dashboard.taskCount": "Task Count",
  "admin.dashboard.administrator": "Administrator",
  "admin.dashboard.dataEntry": "(Data Entry)",
  "admin.dashboard.welcome": "Welcome",
  "admin.dashboard.taskQueue": "Task Queue",
  "admin.dashboard.roleTitle": "Task Roles",
  "admin.dashboard.ptIklRole": "PT(IKL): Check applicant information and documents. Reject to the applicant with remarks if incomplete.",
  "admin.dashboard.kuIklRole": "KU(IKL): Perform second verification, reject if amendment is required, or route complete applications to technical review.",
  "admin.dashboard.unitIklanTechnicalRole": "Advertisement Technical Unit (PT/PO/KP): Conduct site visit, upload site photo, calculate license fee/deposit, and record site remarks.",
  "admin.dashboard.openWorkspace": "Open Unit Workspace",
  "admin.dashboard.queueDescription": "Applications waiting for this unit's action.",
  "admin.dashboard.noTask": "No task to be claimed for this unit.",
  "admin.unit.ikl.desc": "PT(IKL) checks completeness, rejects with remarks when needed, KU(IKL) performs the second verification, and complete applications are routed to technical review.",
  "admin.unit.blg.desc": "BLG performs site inspection and records supported, conditionally supported, or not supported decisions with remarks.",
  "admin.unit.imt.desc": "IMT reviews infrastructure, mapping, and location integration for the advertisement site.",
  "admin.unit.mne.desc": "MNE reviews mechanical and electrical aspects at the advertisement site.",
  "admin.unit.eng.desc": "ENG reviews engineering and structural safety for the advertisement installation.",
  "admin.unit.gpm.desc": "GPM reviews geoinformation, property control, and site suitability.",
  "admin.unit.lnp.desc": "LNP reviews landscape and surrounding-site impact.",
  "admin.workflow.title": "Advertisement License Operational Workflow",
  "admin.workflow.description": "Workflow summary after the applicant submits the application.",
  "admin.workflow.screening": "PT(IKL) and KU(IKL) Screening",
  "admin.workflow.screeningDesc": "PT(IKL) checks information and documents. Incomplete applications are rejected to the applicant with remarks. Complete applications are verified by KU(IKL) before technical review.",
  "admin.workflow.technical": "Technical Site Visit and Review",
  "admin.workflow.technicalDesc": "Advertisement technical officers upload site photos, license fee/deposit calculations, and remarks. BLG, GPM, MNE, IMT, LNP, and ENG record supported, conditionally supported, or not supported decisions.",
  "admin.workflow.management": "KB(LES), TP/PGH, and MPHLG Review",
  "admin.workflow.managementDesc": "KU(IKL) reviews technical reports, KB(LES) verifies, TP/PGH recommends, and MPHLG/SUT records the ministry decision.",
  "admin.workflow.payment": "Approval, Billing, Payment, and QR License",
  "admin.workflow.paymentDesc": "PT(IKL) generates approval letters and invoices, KU(IKL) verifies billing, the applicant pays and uploads proof, then PT(IKL) generates the QR e-license.",
  "admin.workflow.renewal": "License Renewal Reminders",
  "admin.workflow.renewalDesc": "The system creates reminders 3, 2, and 1 month before expiry. If no renewal is made, cancellation and enforcement notices are prepared.",
  "workspace.screening.eyebrow": "PT(IKL) / KU(IKL) Verification",
  "workspace.screening.title": "Application Screening",
  "workspace.screening.description": "Review applicant information and documents. Reject with remarks if incomplete, or route complete applications to KU(IKL)/technical review.",
  "workspace.screening.queue": "Screening Queue",
  "workspace.screening.action": "Record PT(IKL) or KU(IKL) decision for the selected application.",
  "workspace.technical.eyebrow": "Technical Site Visit",
  "workspace.technical.title": "Technical Review",
  "workspace.technical.description": "Record department site visit decision and remarks for IKL review.",
  "workspace.technical.queue": "Technical Queue",
  "workspace.technical.action": "Enter department decision and site finding remarks.",
  "workspace.approval.eyebrow": "KB(LES), TP/PGH, and MPHLG",
  "workspace.approval.title": "Verification and Approval",
  "workspace.approval.description": "Record KB(LES) verification, TP/PGH recommendation, MPHLG/SUT review, and final decision.",
  "workspace.approval.queue": "Approval Queue",
  "workspace.approval.action": "Submit approval decision or remarks.",
  "workspace.payment.eyebrow": "Billing and Payment",
  "workspace.payment.title": "Invoice, Payment Proof, and Verification",
  "workspace.payment.description": "Generate invoices and verify uploaded payment receipt proof.",
  "workspace.payment.queue": "Payment Queue",
  "workspace.payment.action": "Generate an invoice, then verify whether the uploaded receipt is valid or fake.",
  "workspace.license.eyebrow": "QR E-License and Renewal",
  "workspace.license.title": "QR License and Renewal Reminders",
  "workspace.license.description": "Generate QR e-license, monitor expiry, and issue renewal reminders.",
  "workspace.license.queue": "License Queue",
  "workspace.license.action": "Issue, revoke, or monitor the digital license.",
  "workspace.queue.instructions": "Select a record, then complete the action panel.",
  "workspace.search.placeholder": "Search reference, applicant, project, type, or location",
  "workspace.empty": "No applications found.",
  "workspace.actionPanel": "Action Panel",
  "workspace.selectApplication": "Select an application.",
  "workspace.openForm": "View Form",
  "workspace.backToDashboard": "Back to Dashboard",
  "workspace.saving": "Saving...",
  "workspace.selectedRecord": "Selected Record",
  "workspace.selectedRecordDesc": "Key information from the backend application record.",
  "workspace.selectedApplication": "Selected Application",
  "workspace.defaultApplicationTitle": "Advertisement License Application",
  "application.type.siteNew": "Application for Site (New Site)",
  "application.type.site": "Application for Site",
  "application.type.sitting": "Sitting Application",
  "application.type.signboard": "Signboard License",
  "application.type.buildingPlan": "Building Plan",
  "workspace.created": "Created",
  "workspace.step": "Step",
  "workspace.location": "Location",
  "workspace.decision.completeToKu": "PT(IKL) Send to KU(IKL)",
  "workspace.decision.kuToTechnical": "KU(IKL) Confirm - Send to Technical Units",
  "workspace.decision.rejectApplicant": "PT(IKL) Reject to Applicant",
  "workspace.decision.kuRejectApplicant": "KU(IKL) Reject to Applicant",
  "workspace.decision.technicalAmendment": "Technical Amendment Required",
  "workspace.decision.supported": "Supported",
  "workspace.decision.supportedConditions": "Supported with Conditions",
  "workspace.decision.notSupported": "Not Supported",
  "workspace.decision.kuConfirmToKb": "KU(IKL) Confirm - Send to KB(LES)",
  "workspace.decision.kuRequestTechnicalAmendment": "KU(IKL) Request Technical Amendment",
  "workspace.decision.requiresAmendment": "Requires Amendment",
  "workspace.decision.approved": "Approved",
  "workspace.decision.approvedConditions": "Approved with Conditions",
  "workspace.decision.rejected": "Rejected",
  "workspace.comment.remarks": "Remarks",
  "workspace.comment.screeningPlaceholder": "Enter PT(IKL) / KU(IKL) remarks. Required when rejecting.",
  "workspace.ikl.screeningTitle": "PT(IKL) / KU(IKL) Verification",
  "workspace.ikl.screeningDesc": "Use this section to send to KU(IKL), send to technical review, or reject to the applicant with remarks.",
  "workspace.comment.technical": "Remarks",
  "workspace.comment.technicalPlaceholder": "Add department comments, conditions, site notes, or rejection reasons.",
  "workspace.technical.siteVisitTitle": "Advertisement Unit Site Visit",
  "workspace.technical.siteVisitDesc": "Record the PT/PO/KP function: site photo, advertisement license fee calculation, deposit, and site finding remarks.",
  "workspace.technical.sitePhoto": "Site Photo",
  "workspace.technical.uploadSitePhoto": "Upload Site Photo",
  "workspace.technical.sitePhotoUploaded": "Site photo uploaded",
  "workspace.technical.licenseFee": "Advertisement License Fee Calculation (RM)",
  "workspace.technical.deposit": "Deposit Calculation (RM)",
  "workspace.technical.siteRemarks": "Site Finding Remarks",
  "workspace.technical.siteRemarksPlaceholder": "Enter site visit findings, location issues, conditions, or other remarks.",
  "workspace.technical.awaitingDepartmentReviews": "Complete BLG, GPM, MNE, IMT, LNP, and ENG feedback before recording the final technical decision.",
  "workspace.technical.kuReviewTitle": "KU(IKL) Technical Review",
  "workspace.technical.kuReviewDesc": "Review the final technical decision, license fee, deposit, and remarks before requesting amendment or routing to KB(LES).",
  "workspace.technical.kuReviewPlaceholder": "Enter KU(IKL) remarks, amendment reason, or instructions for the next review.",
  "workspace.technical.compiledRemarksTitle": "Technical Department Remarks",
  "workspace.technical.compiledRemarksDesc": "Feedback from BLG, GPM, MNE, IMT, LNP, and ENG updates here for IKL review.",
  "workspace.comment.approval": "Approval Notes",
  "workspace.comment.payment": "Receipt Verification Notes",
  "workspace.comment.paymentPlaceholder": "Add verification notes, receipt issues, or rejection reason.",
  "workspace.action.submitScreening": "Submit PT/KU Decision",
  "workspace.action.submitKuTechnicalReview": "Submit KU(IKL) Review",
  "workspace.action.submitReview": "Submit Review",
  "workspace.action.submitSiteVisit": "Submit Site Visit",
  "workspace.action.submitDecision": "Submit Decision",
  "workspace.action.generateInvoice": "Generate Invoice",
  "workspace.action.submitPayment": "Submit Payment",
  "workspace.action.verifyPayment": "Verify Receipt",
  "workspace.action.rejectReceipt": "Reject Receipt",
  "workspace.action.issueLicense": "Issue License",
  "workspace.action.revoke": "Revoke",
  "workspace.message.screeningSaved": "Screening decision saved.",
  "workspace.message.technicalSaved": "Technical review saved.",
  "workspace.message.kuTechnicalReviewSaved": "KU(IKL) technical review saved.",
  "workspace.message.siteVisitSaved": "Site visit saved.",
  "workspace.message.decisionSaved": "Final decision saved.",
  "workspace.message.invoiceGenerated": "Invoice generated.",
  "workspace.message.paymentRecorded": "Payment submission recorded.",
  "workspace.message.paymentVerified": "Payment verified.",
  "workspace.message.receiptRejected": "Receipt rejected. Applicant can upload a new receipt.",
  "workspace.message.licenseIssued": "E-license issued.",
  "workspace.message.licenseRevoked": "License revoked.",
  "workspace.stat.total": "Total",
  "workspace.stat.pending": "Pending",
  "workspace.stat.screened": "Screened",
  "workspace.stat.passed": "Passed",
  "workspace.stat.completed": "Completed",
  "workspace.stat.supported": "Supported",
  "workspace.stat.notSupported": "Not Supported",
  "workspace.stat.awaiting": "Awaiting",
  "workspace.stat.approved": "Approved",
  "workspace.stat.conditional": "Conditional",
  "workspace.stat.rejected": "Rejected",
  "workspace.stat.invoiced": "Invoiced",
  "workspace.stat.submitted": "Submitted",
  "workspace.stat.verified": "Verified",
  "workspace.stat.issued": "Issued",
  "workspace.stat.revoked": "Revoked",
  "workspace.stat.active": "Active",
  "workspace.check.applicationForm": "Application form",
  "workspace.check.location": "GIS / location",
  "workspace.check.supportingDocuments": "Supporting documents",
  "workspace.check.blacklist": "Blacklist check",
  "workspace.check.duplicateLocation": "Duplicate location check",
  "workspace.check.declaration": "Applicant declaration",
  "workspace.check.passed": "Passed",
  "workspace.check.failed": "Failed",
  "workspace.check.warning": "Warning",
  "workspace.info.licenseId": "License ID",
  "workspace.info.expiry": "Expiry",
  "workspace.info.verificationUrl": "Verification URL",
  "workspace.info.receipt": "Receipt",
  "workspace.info.viewReceipt": "View receipt",
  "workspace.info.verificationResult": "Verification Result",
  "workspace.info.verificationNotes": "Verification Notes",
  "workspace.info.notGenerated": "Not generated",
  "workspace.info.notSubmitted": "Not submitted",
  "workspace.info.pendingIssuance": "Pending issuance",
};

const dictionaries = {
  ms: {
    ...adminWorkflowMs,
    "app.system": "Sistem ALiS",
    "app.portal": "Portal ALiS",
    "app.license": "Lesen Iklan Digital",
    "app.workflow": "Aliran Kelulusan MPHLG",
    "common.language": "Bahasa",
    "common.malay": "BM",
    "common.english": "EN",
    "common.logout": "Log Keluar",
    "common.notifications": "Notifikasi",
    "common.latestUpdates": "Kemas kini ALiS terkini",
    "common.new": "Baharu",
    "common.noNotifications": "Tiada notifikasi",
    "common.markAllRead": "Tanda semua dibaca",
    "common.viewAll": "Lihat semua",
    "common.help": "Bantuan",
    "common.and": "dan",
    "common.loading": "Memuatkan...",
    "common.loadingSelectedApplication": "Memuatkan permohonan dipilih...",
    "common.reset": "Set Semula",
    "common.cancel": "Batal",
    "common.edit": "Sunting",
    "common.save": "Simpan",
    "common.saving": "Menyimpan...",
    "common.submit": "Hantar",
    "common.submitting": "Menghantar...",
    "common.signIn": "Log Masuk",
    "common.signingIn": "Sedang log masuk...",
    "common.registerNow": "Daftar Sekarang",
    "common.newApplication": "Permohonan Baharu",
    "common.continue": "Teruskan",
    "common.view": "Lihat",
    "common.manage": "Urus",
    "common.download": "Muat Turun",
    "common.delete": "Padam",
    "common.ready": "Sedia",
    "common.waiting": "Menunggu",
    "common.complete": "Selesai",
    "common.notComplete": "Belum selesai",
    "common.pending": "Belum selesai",
    "common.done": "Selesai",
    "common.search": "Carian",
    "common.searchAndFilter": "Carian & Penapis",
    "common.keyword": "Kata Kunci",
    "common.month": "Bulan",
    "common.year": "Tahun",
    "common.allMonths": "Semua Bulan",
    "common.allYears": "Semua Tahun",
    "common.clearFilters": "Kosongkan Penapis",
    "common.status": "Status",
    "common.allStatuses": "Semua status",
    "common.total": "Jumlah",
    "common.drafts": "Draf",
    "common.submitted": "Dihantar",
    "common.paymentAction": "Bukti Bayaran",
    "common.eLicenses": "E-Lesen",
    "common.reference": "Rujukan",
    "common.project": "Projek",
    "common.type": "Jenis",
    "common.department": "Bahagian",
    "common.updated": "Dikemas Kini",
    "common.action": "Tindakan",
    "common.open": "Buka",
    "common.invoice": "Invois",
    "common.amount": "Amaun",
    "common.paymentStatus": "Status Bayaran",
    "common.receiptReference": "Rujukan Resit",
    "common.receipt": "Resit",
    "common.uploadReceipt": "Muat Naik Resit",
    "common.application": "Permohonan",
    "common.applicant": "Pemohon",
    "common.lastUpdated": "Terakhir dikemas kini",
    "common.notification": "Notifikasi",
    "common.copyright": "© 2026 Permohonan Lesen Iklan. Hak Cipta Terpelihara.",
    "notifications.eyebrow": "Pusat Notifikasi Langsung",
    "notifications.title": "Notifikasi",
    "notifications.description": "Makluman langsung yang dijana daripada status permohonan, keputusan aliran kerja, bayaran dan rekod e-lesen QR.",
    "notifications.refresh": "Segar Semula",
    "notifications.unread": "Belum Dibaca",
    "notifications.actionRequired": "Perlu Tindakan",
    "notifications.licensePayment": "Bayaran / Lesen",
    "notifications.inbox": "Peti Masuk",
    "notifications.lastSynced": "Segerak terakhir",
    "notifications.waitingForSync": "Menunggu segerakan langsung.",
    "notifications.liveInbox": "Peti Masuk Langsung",
    "notifications.records": "rekod",
    "notifications.emptyDescription": "Notifikasi akan muncul di sini apabila permohonan memerlukan tindakan atau berubah status.",
    "notifications.markRead": "Tanda Dibaca",
    "notifications.openRecord": "Lihat",
    "notifications.filter.all": "Semua",
    "notifications.filter.unread": "Belum Dibaca",
    "notifications.filter.account": "Akaun",
    "notifications.filter.screening": "Semakan",
    "notifications.filter.technical": "Teknikal",
    "notifications.filter.approval": "Kelulusan",
    "notifications.filter.payment": "Bayaran",
    "notifications.filter.license": "Lesen",
    "notifications.filter.correction": "Pembetulan",
    "notifications.filter.decision": "Keputusan",
    "notifications.filter.progress": "Kemajuan",
    "common.nextStep": "Langkah seterusnya",
    "common.decision": "Keputusan",
    "common.remark": "Catatan",
    "common.date": "Tarikh",
    "common.currentPhase": "Fasa Semasa",
    "app.digitalLicenseSystem": "Sistem Lesen Digital",
    "app.advertisementLicenseApplication": "Permohonan Lesen Iklan",
    "app.digitalLicensePortal": "Permohonan Lesen Iklan",
    "app.digitalAdvertisementLicense": "Lesen Iklan Digital",
    "app.digitalAdvertisementLicenseSystem": "Permohonan Lesen Iklan",
    "app.authFeatureSubmit": "Penyerahan Permohonan Iklan Dan Dokumen Sokongan Secara Dalam Talian.",
    "app.authFeatureTrack": "Semakan Status Permohonan",
    "role.admin": "Pentadbir",
    "role.officer": "Pegawai ALiS",
    "role.applicant": "Pemohon",
    "role.officerPortal": "Portal Pegawai",
    "role.applicantPortal": "Portal Pemohon",
    "role.ALiSUser": "Pengguna ALiS",
    "profile.welcome": "Selamat datang",
    "profile.profile": "Profil",
    "profile.accountProfile": "Profil Akaun",
    "profile.accountRegistrationInfo": "Maklumat daripada pendaftaran akaun anda.",
    "profile.backToDashboard": "Kembali ke Papan Pemuka",
    "profile.leavePasswordBlank": "Biarkan kosong jika tidak mahu menukar kata laluan",
    "profile.saveSuccess": "Maklumat profil berjaya dikemas kini.",
    "profile.saveFailed": "Maklumat profil gagal dikemas kini.",
    "nav.overview": "Gambaran",
    "nav.home": "Laman Utama",
    "nav.dashboard": "Papan Pemuka",
    "superadmin.nav.users": "Pengguna",
    "superadmin.nav.admins": "Admin",
    "nav.myDashboard": "Papan Pemuka Saya",
    "nav.applicationFlow": "Aliran Permohonan",
    "nav.applications": "Permohonan",
    "nav.guidelines": "Panduan",
    "nav.myApplications": "Permohonan Saya",
    "nav.verification": "Verifikasi S2",
    "nav.technical": "Teknikal",
    "nav.approval": "Kelulusan",
    "nav.payment": "Bayaran",
    "nav.license": "E-Lesen / QR",
    "nav.enforcement": "Penguatkuasaan",
    "nav.reports": "Laporan",
    "nav.notifications": "Notifikasi",
    "dashboard.eyebrow": "Sistem ALiS",
    "dashboard.title": "Papan Pemuka Lesen Iklan",
    "dashboard.description":
      "Pantau permohonan lesen iklan digital mengikut sasaran 25 hari: pendaftaran, verifikasi, teknikal, perakuan, MPHLG, kelulusan, bayaran dan e-lesen.",
    "dashboard.total": "Jumlah Permohonan",
    "dashboard.totalNote": "Semua permohonan lesen iklan",
    "dashboard.underReview": "Dalam Semakan",
    "dashboard.underReviewNote": "Menunggu tindakan bahagian lesen atau teknikal",
    "dashboard.pendingPayment": "Menunggu Bayaran",
    "dashboard.pendingPaymentNote": "Diluluskan tetapi bayaran belum selesai",
    "dashboard.licensesIssued": "Lesen Dikeluarkan",
    "dashboard.licensesIssuedNote": "E-lesen aktif",
    "dashboard.statusSummary": "Ringkasan Status Permohonan",
    "dashboard.statusSummaryDesc": "Jumlah permohonan mengikut fasa carta alir.",
    "dashboard.sla": "Pemantauan SLA",
    "dashboard.slaDesc": "Sasaran keseluruhan sistem ialah 25 hari.",
    "dashboard.recent": "Permohonan Terkini",
    "dashboard.recentDesc": "Permohonan lesen iklan yang diterima atau sedang diproses.",
    "dashboard.flow": "Carta Alir Sistem",
    "dashboard.flowDesc": "Urutan proses lesen iklan digital seperti carta MPHLG.",
    "dashboard.departmentPerformance": "Prestasi Bahagian / Agensi",
    "dashboard.departmentDesc": "Pantau tugasan, tindakan tertunggak dan selesai mengikut peranan.",
    "auth.loginTitle": "Log Masuk",
    "auth.welcome": "Selamat Datang",
    "auth.loginDescription": "Akses papan pemuka dan perkhidmatan anda.",
    "auth.malaysian": "Warganegara Malaysia",
    "auth.icNumber": "Nombor MyKad",
    "auth.loginIdentifier": "Nombor MyKad / ID Admin",
    "auth.emailAddress": "Alamat E-mel",
    "auth.password": "Kata Laluan",
    "auth.rememberMe": "Ingat saya",
    "auth.forgotPassword": "Lupa Kata Laluan?",
    "auth.reset.eyebrow": "Pemulihan Akaun",
    "auth.reset.title": "Tetapkan semula kata laluan",
    "auth.reset.description": "Masukkan e-mel berdaftar anda, pilih cara menerima OTP, kemudian cipta kata laluan baharu selepas pengesahan berjaya.",
    "auth.reset.stepEmail": "E-mel",
    "auth.reset.stepWhatsapp": "WhatsApp",
    "auth.reset.stepOtp": "OTP",
    "auth.reset.stepPassword": "Kata Laluan",
    "auth.reset.emailPlaceholder": "cth. nama@email.com",
    "auth.reset.whatsappNumber": "Nombor WhatsApp",
    "auth.reset.whatsappPlaceholder": "cth. 60123456789",
    "auth.reset.chooseChannel": "Terima OTP melalui",
    "auth.reset.channelEmail": "E-mel",
    "auth.reset.channelEmailDesc": "Hantar OTP ke e-mel berdaftar.",
    "auth.reset.channelWhatsapp": "WhatsApp",
    "auth.reset.channelWhatsappDesc": "Hantar OTP ke nombor telefon berdaftar.",
    "auth.reset.getOtp": "Dapatkan OTP",
    "auth.reset.sendingOtp": "Menghantar OTP...",
    "auth.reset.otpSent": "OTP telah dihantar. Sila semak saluran pilihan anda.",
    "auth.reset.devOtp": "OTP pembangunan",
    "auth.reset.enterOtp": "Masukkan 6 digit OTP",
    "auth.reset.otpDigit": "Digit OTP",
    "auth.reset.otpHint": "OTP tamat tempoh dalam 10 minit. Jangan kongsi OTP ini dengan orang lain.",
    "auth.reset.enterCompleteOtp": "Sila masukkan keenam-enam digit OTP.",
    "auth.reset.verifyOtp": "Sahkan OTP",
    "auth.reset.verifying": "Mengesahkan OTP...",
    "auth.reset.resendOtp": "Hantar semula OTP",
    "auth.reset.otpVerified": "OTP disahkan. Sila cipta kata laluan baharu.",
    "auth.reset.newPassword": "Kata Laluan Baharu",
    "auth.reset.savePassword": "Simpan Kata Laluan Baharu",
    "auth.reset.passwordMin": "Kata laluan mesti sekurang-kurangnya 8 aksara.",
    "auth.reset.successLogin": "Kata laluan berjaya ditetapkan semula. Sila log masuk menggunakan kata laluan baharu anda.",
    "auth.reset.checkEmail": "Sila semak alamat e-mel yang dimasukkan.",
    "auth.reset.checkWhatsapp": "Sila semak nombor WhatsApp yang dimasukkan.",
    "auth.reset.validationWhatsapp": "Sila masukkan nombor WhatsApp berdaftar anda.",
    "auth.reset.validationWhatsappFormat": "Sila masukkan nombor WhatsApp yang sah.",
    "auth.reset.errorGeneric": "Kami tidak dapat memproses permintaan ini sekarang. Sila cuba lagi.",
    "auth.reset.errorNotFound": "Tiada akaun ALiS dijumpai untuk alamat e-mel tersebut.",
    "auth.reset.errorNotFoundWhatsapp": "Tiada akaun ALiS dijumpai untuk nombor WhatsApp tersebut.",
    "auth.reset.errorExpired": "OTP atau sesi tetapan semula telah tamat tempoh. Sila minta OTP baharu.",
    "auth.reset.errorTooMany": "Terlalu banyak percubaan OTP yang salah. Sila minta OTP baharu.",
    "auth.reset.errorNoWhatsapp": "Akaun ini belum mempunyai nombor WhatsApp/telefon berdaftar. Sila pilih e-mel.",
    "auth.reset.errorNoEmail": "Akaun ini belum mempunyai alamat e-mel berdaftar.",
    "auth.noAccount": "Belum ada akaun?",
    "auth.enterIcPassword": "Sila masukkan Nombor MyKad dan kata laluan.",
    "auth.validation.loginIc": "Sila masukkan Nombor MyKad anda.",
    "auth.validation.loginIdentifier": "Sila masukkan Nombor MyKad atau ID Admin anda.",
    "auth.validation.loginPassword": "Sila masukkan kata laluan anda.",
    "auth.validation.loginMykadFormat": "Nombor MyKad mesti mengandungi 12 digit tanpa sengkang.",
    "auth.validation.loginIdentifierFormat": "Sila masukkan Nombor MyKad 12 digit atau ID Admin yang sah.",
    "auth.enterEmailPassword": "Sila masukkan e-mel dan kata laluan.",
    "auth.loginIcFailed": "Maklumat log masuk salah. Sila semak Nombor MyKad dan kata laluan anda.",
    "auth.loginEmailFailed": "Log masuk gagal. Sila semak e-mel dan kata laluan anda.",
    "auth.registrationTitle": "Pendaftaran Akaun",
    "auth.registrationMalaysianDescription": "Lengkapkan borang di bawah untuk mencipta akaun anda. Pastikan semua maklumat sepadan dengan dokumen pengenalan rasmi anda.",
    "auth.personalInformation": "Maklumat Peribadi",
    "auth.fullNameMyKad": "Nama Penuh (seperti MyKad)",
    "auth.fullNamePlaceholder": "Masukkan nama penuh rasmi anda",
    "auth.gender": "Jantina",
    "auth.selectGender": "Pilih jantina",
    "auth.genderMale": "Lelaki",
    "auth.genderFemale": "Perempuan",
    "auth.dateOfBirth": "Tarikh Lahir",
    "auth.nationality": "Kewarganegaraan",
    "auth.mykadNumber": "Nombor MyKad",
    "auth.enterWithoutDashes": "Masukkan tanpa sengkang",
    "auth.contactDetails": "Butiran Perhubungan",
    "auth.mobileNumber": "Nombor Telefon Bimbit",
    "auth.address": "Alamat",
    "auth.addressLine1": "Unit / Tingkat / Blok",
    "auth.addressLine2": "Jalan & Kawasan Perumahan",
    "auth.addressLine1Placeholder": "cth. Unit 3A, Tingkat 2, Blok B",
    "auth.addressLine2Placeholder": "cth. Jalan Satok, Taman Satok",
    "auth.postcode": "Poskod",
    "auth.city": "Bandar",
    "auth.selectCity": "Pilih bandar",
    "auth.selectStateFirst": "Pilih negeri dahulu",
    "auth.state": "Negeri",
    "auth.selectState": "Pilih negeri",
    "auth.accountSecurity": "Keselamatan Akaun",
    "auth.retypePassword": "Taip Semula Kata Laluan",
    "auth.confirmPassword": "Sahkan Kata Laluan",
    "auth.captchaVerification": "Pengesahan CAPTCHA",
    "auth.notRobot": "Saya bukan robot",
    "auth.verification": "Pengesahan",
    "auth.privacyTerms": "Privasi - Terma",
    "auth.localCaptchaPreview": "Pratonton tempatan sahaja. Tambah kunci laman Google reCAPTCHA untuk memaparkan widget sebenar.",
    "auth.submitRegistration": "Hantar Pendaftaran",
    "auth.backToLogin": "Kembali ke Log Masuk",
    "auth.registerSuccess": "Pendaftaran berjaya. Sila log masuk untuk meneruskan.",
    "auth.registerSuccessLogin": "Pendaftaran akaun berjaya. Sila log masuk menggunakan Nombor MyKad dan kata laluan yang telah didaftarkan.",
    "auth.registerFailed": "Pendaftaran gagal. Sila semak maklumat anda.",
    "auth.recaptchaLoadFailed": "reCAPTCHA tidak dapat dimuatkan. Sila cuba lagi.",
    "auth.recaptchaConnectionFailed": "reCAPTCHA tidak dapat dimuatkan. Sila semak sambungan anda.",
    "auth.validation.fullName": "Sila masukkan nama penuh anda.",
    "auth.validation.summary": "Sila semak medan yang ditandakan dan lengkapkan maklumat yang diperlukan.",
    "auth.validation.gender": "Sila pilih jantina anda.",
    "auth.validation.dateOfBirth": "Sila masukkan tarikh lahir anda.",
    "auth.validation.nationality": "Sila masukkan kewarganegaraan anda.",
    "auth.validation.mykad": "Sila masukkan Nombor MyKad anda.",
    "auth.validation.mykadFormat": "Nombor MyKad mesti mengandungi 12 digit tanpa sengkang.",
    "auth.validation.mobile": "Sila masukkan nombor telefon bimbit anda.",
    "auth.validation.email": "Sila masukkan alamat e-mel anda.",
    "auth.validation.emailFormat": "Sila masukkan alamat e-mel yang sah.",
    "auth.validation.mykadExists": "Nombor MyKad ini telah didaftarkan. Sila log masuk atau gunakan Nombor MyKad lain.",
    "auth.validation.emailExists": "Alamat e-mel ini telah didaftarkan. Sila gunakan alamat e-mel lain.",
    "auth.validation.addressLine1": "Sila masukkan unit, tingkat atau blok anda.",
    "auth.validation.addressLine2": "Sila masukkan jalan dan kawasan perumahan anda.",
    "auth.validation.addressLine1Length": "Unit / Tingkat / Blok tidak boleh melebihi 150 aksara.",
    "auth.validation.addressLine2Length": "Jalan & Kawasan Perumahan tidak boleh melebihi 150 aksara.",
    "auth.validation.postcode": "Sila masukkan poskod anda.",
    "auth.validation.city": "Sila masukkan bandar anda.",
    "auth.validation.state": "Sila pilih negeri anda.",
    "auth.validation.password": "Sila masukkan kata laluan anda.",
    "auth.validation.confirmPassword": "Sila sahkan kata laluan anda.",
    "auth.validation.passwordMismatch": "Kata Laluan dan Sahkan Kata Laluan tidak sepadan.",
    "auth.validation.recaptcha": "Sila lengkapkan pengesahan reCAPTCHA.",
    "auth.validation.captcha": "Sila lengkapkan pengesahan CAPTCHA.",
    "auth.validation.recaptchaFailed": "Pengesahan reCAPTCHA gagal. Sila cuba lagi.",
    "auth.copyright": "Hak Cipta Terpelihara.",
    "auth.termsService": "Terma Perkhidmatan",
    "auth.faq": "Soalan Lazim",
    "auth.contactUs": "Hubungi Kami",
    "faq.title": "Soalan Lazim (FAQ)",
    "faq.description": "Rujukan pantas untuk membantu anda menggunakan portal permohonan lesen iklan ALiS.",
    "faq.createApplication.question": "Bagaimana saya mencipta permohonan baharu?",
    "faq.createApplication.answer": "Selepas log masuk, klik butang Submit New Application pada papan pemuka anda dan lengkapkan semua medan wajib. Muat naik semua dokumen yang diperlukan dan hantar permohonan.",
    "faq.rejected.question": "Apakah yang perlu saya lakukan jika permohonan saya ditolak?",
    "faq.rejected.answer": "Semak ulasan yang diberikan bersama notifikasi penolakan. Betulkan isu yang dinyatakan dalam permohonan anda dan hantar semula.",
    "faq.payment.question": "Bagaimana saya membuat pembayaran?",
    "faq.payment.answer": "Setelah permohonan anda diluluskan, anda akan menerima bil. Anda boleh membuat bayaran melalui perbankan dalam talian atau secara tunai di kaunter yang ditetapkan. Selepas bayaran dibuat, muat naik bukti pembayaran dalam portal.",
    "faq.renewLicense.question": "Bagaimana saya memperbaharui lesen saya?",
    "faq.renewLicense.answer": "Anda akan menerima peringatan pembaharuan sebelum lesen tamat tempoh. Ikut arahan dalam peringatan tersebut untuk menghantar permohonan pembaharuan dan membuat pembayaran.",
    "faq.contactHelp.question": "Siapa yang boleh saya hubungi untuk mendapatkan bantuan?",
    "faq.contactHelp.answer": "Untuk bantuan, sila e-mel support@example.com atau hubungi +60 123 456 789 semasa waktu pejabat.",
    "applicant.portal": "Portal Pemohon",
    "applicant.records": "Rekod Pemohon",
    "applicant.dashboardTitle": "Permohonan Lesen Iklan Saya",
    "applicant.dashboardDescription": "Mulakan permohonan dalam talian, muat naik dokumen, jejak status secara masa nyata, terima keputusan, selesaikan bayaran dan muat turun e-lesen QR.",
    "applicant.applicationsTitle": "Permohonan Saya",
    "applicant.applicationsDescription": "Jejak setiap permohonan daripada draf hingga verifikasi S2, semakan teknikal, kelulusan, bayaran dan e-lesen QR.",
    "applicant.workspaceTitle": "Ruang Kerja Permohonan",
    "applicant.totalApplications": "Jumlah Permohonan",
    "applicant.currentProgress": "Kemajuan Semasa",
    "applicant.statusTrackingDescription": "Jejaki kemajuan setiap permohonan yang telah dihantar sehingga keputusan, bayaran dan e-lesen.",
    "applicant.noApplicationSubmitted": "Belum ada permohonan dihantar.",
    "applicant.createApplicationHint": "Cipta permohonan baharu untuk memulakan fasa pendaftaran.",
    "applicant.flowTitle": "Pemohon (Modul Front-End)",
    "applicant.flowDescription": "Aliran lengkap pemohon selepas log masuk mengikut carta lesen iklan digital.",
    "applicant.startTitle": "Mula",
    "applicant.startDesc": "Pemohon masuk ke portal.",
    "applicant.s1Title": "Akses Portal & Log Masuk",
    "applicant.s1Desc": "Papan pemuka pemohon dan akaun aktif.",
    "applicant.formUploadTitle": "Isi Borang & Muat Naik Dokumen",
    "applicant.formUploadDesc": "Lengkapkan 11 langkah dan dokumen sokongan.",
    "applicant.statusCompleteTitle": "Status Lengkap?",
    "applicant.correctionEmailDesc": "Tindakan pembetulan melalui e-mel.",
    "applicant.memoDesc": "Jika lengkap, memo dalaman dijana.",
    "applicant.memoTitle": "Status 'Lengkap', Jana Memo Dalaman",
    "applicant.memoMoveDesc": "Permohonan bergerak ke Bahagian Lesen.",
    "applicant.decisionNoticeTitle": "Terima Notifikasi Keputusan",
    "applicant.decisionNoticeDesc": "Makluman lulus, lulus bersyarat atau tidak lulus.",
    "applicant.onlinePaymentTitle": "Muat Naik Resit Bayaran",
    "applicant.onlinePaymentDesc": "Muat naik resit bayaran selepas invois dijana.",
    "applicant.licenseDownloadTitle": "Muat Turun E-Lesen (Kod QR)",
    "applicant.licenseDownloadDesc": "E-lesen QR boleh dimuat turun selepas lesen dikeluarkan.",
    "applicant.endTitle": "Tamat",
    "applicant.endDesc": "Aliran pemohon selesai.",
    "applicant.applicationSelected": "Permohonan dipilih",
    "applicant.noApplicationYet": "Belum ada permohonan",
    "applicant.startRequired": "Perlu mula",
    "applicant.dashboardHeaderTitle": "Papan Pemuka",
    "applicant.dashboardHeaderDescription": "Semak tindakan seterusnya, sediakan maklumat permohonan dan pantau urusan lesen iklan anda.",
    "applicant.statusCorrection": "T: Pembetulan",
    "applicant.statusCompleteYes": "Y: Lengkap",
    "applicant.actionsTitle": "Tindakan Pemohon",
    "applicant.actionsDescription": "Lengkapkan tindakan pemohon daripada permohonan, pembetulan, notifikasi keputusan, bayaran hingga e-lesen QR.",
    "applicant.actionsEmptyDescription": "Cipta permohonan baharu untuk mengaktifkan tindakan pemohon.",
    "applicant.s1ActionTitle": "Akses portal, log masuk, lengkapkan borang dan muat naik dokumen",
    "applicant.actionRequired": "Tindakan diperlukan",
    "applicant.completed": "Selesai",
    "applicant.continueApplication": "Teruskan Permohonan",
    "applicant.viewSubmission": "Lihat Hantaran",
    "applicant.correctionTitle": "Terima notifikasi pembetulan dan kemas kini maklumat tidak lengkap",
    "applicant.correctionRequired": "Pembetulan diperlukan",
    "applicant.noCorrectionRequest": "Tiada permintaan pembetulan",
    "applicant.emailCorrectionRequested": "Pembetulan melalui e-mel diminta",
    "applicant.noActiveCorrectionNotice": "Tiada notis pembetulan aktif",
    "applicant.updateApplicationForm": "Kemas kini borang permohonan",
    "applicant.waitLicensingReview": "Tunggu semakan Bahagian Lesen",
    "applicant.openCorrection": "Buka Pembetulan",
    "applicant.receiveDecisionTitle": "Terima notifikasi keputusan daripada fasa kelulusan",
    "applicant.paymentByFpxCard": "Muat naik resit bayaran",
    "applicant.waitingInvoice": "Menunggu invois",
    "applicant.notSubmitted": "Belum dihantar",
    "applicant.submitPayment": "Hantar Resit",
    "applicant.selectedApplication": "Permohonan Dipilih",
    "applicant.downloadQrELicense": "Muat Turun E-Lesen QR",
    "applicant.qrLicensePending": "E-lesen QR akan dipaparkan selepas bayaran disahkan dan lesen dikeluarkan.",
    "applicant.workflowInactive": "Tiada aliran kerja pemohon aktif lagi.",
    "applicant.overviewTitle": "Gambaran Papan Pemuka",
    "applicant.overviewDescription": "Semak ringkasan permohonan, tindakan seterusnya, status hantaran dan e-lesen anda dari satu tempat.",
    "applicant.latestActivity": "Aktiviti Terkini",
    "applicant.dashboardEmptyOverview": "Belum ada aktiviti permohonan. Mulakan permohonan baharu untuk melihat kemajuan dan status di sini.",
    "applicant.nextActionStartTitle": "Mulakan permohonan lesen iklan anda",
    "applicant.nextActionStartDescription": "Sediakan maklumat projek, butiran orang yang mengemukakan dan dokumen sokongan sebelum menghantar permohonan kepada ALiS.",
    "applicant.nextActionDraftTitle": "Sambung draf permohonan anda",
    "applicant.nextActionDraftDescription": "Teruskan langkah permohonan yang belum lengkap dan hantar apabila semua maklumat serta dokumen sudah sedia.",
    "applicant.nextActionSubmittedTitle": "Pantau perkembangan permohonan",
    "applicant.nextActionSubmittedDescription": "Permohonan anda telah direkodkan. Semak status, keputusan, bayaran dan e-lesen daripada portal ini.",
    "applicant.beforeApplyTitle": "Sebelum Memohon",
    "applicant.beforeApplyDescription": "Pastikan maklumat utama ini tersedia supaya proses pengisian lebih lancar.",
    "applicant.dashboardChecklistProject": "Maklumat projek dan lokasi tapak iklan",
    "applicant.dashboardChecklistPerson": "Butiran orang yang mengemukakan dan nombor telefon",
    "applicant.dashboardChecklistDocuments": "Dokumen sokongan untuk dimuat naik",
    "applicant.dashboardChecklistDeclaration": "Semakan akhir sebelum akuan dan cetakan borang",
    "applicant.calendarTitle": "Kalendar",
    "applicant.calendarActivityHint": "Titik hijau menandakan tarikh aktiviti permohonan.",
    "applicant.calendarEmptyHint": "Aktiviti permohonan akan ditandakan di sini selepas rekod diwujudkan.",
    "applicant.applicationJourneyTitle": "Aliran Permohonan",
    "applicant.applicationJourneyDescription": "Lengkapkan langkah berikut sebelum permohonan dihantar untuk semakan.",
    "applicant.myApplicationsDesc": "Senarai bersih rekod draf dan hantaran anda.",
    "applicant.applicationsSectionTitle": "Permohonan",
    "applicant.applicationsSectionDescription": "Cipta permohonan baharu, sambung draf, cari rekod dan urus hantaran permohonan lesen iklan anda.",
    "applicant.statusSectionTitle": "Status Permohonan",
    "applicant.licenseSectionTitle": "E-Lesen dan Bukti Bayaran",
    "applicant.licenseSectionDescription": "Muat naik bukti bayaran, semak pengesahan bayaran dan muat turun e-lesen QR apabila tersedia.",
    "applicant.tabApplications": "Permohonan",
    "applicant.tabStatus": "Status",
    "applicant.tabPayment": "Bayaran",
    "applicant.tabLicense": "E-Lesen",
    "applicant.paymentProofTitle": "Bukti Bayaran",
    "applicant.noApplicationsYet": "Belum ada permohonan.",
    "applicant.searchPlaceholder": "Cari rujukan, projek, jenis atau status",
    "applicant.searchFilterHint": "Tapis rekod mengikut kata kunci, bulan permohonan dan tahun permohonan.",
    "applicant.applicationList": "Senarai Permohonan",
    "applicant.recordsFound": "rekod dijumpai.",
    "applicant.submittedApplications": "permohonan dihantar",
    "applicant.noUserApplications": "Anda belum mempunyai permohonan.",
    "applicant.paymentSubmittedSuccess": "Resit bayaran telah dihantar. ALiS akan mengesahkannya sebelum e-lesen QR dikeluarkan.",
    "applicant.paymentSubmissionFailed": "Hantaran bayaran gagal.",
    "applicant.receiptUploadRequired": "Sila muat naik resit bayaran sebelum menghantar.",
    "applicant.receiptUploadFailed": "Muat naik resit gagal.",
    "applicant.chooseReceiptFile": "Pilih fail resit",
    "applicant.receiptUploadHint": "PDF atau imej diterima sebagai bukti bayaran.",
    "applicant.detailsLoadFailed": "Tidak dapat memuatkan butiran permohonan dipilih.",
    "applicant.paymentHintDraft": "Lengkapkan dan hantar permohonan sebelum bayaran tersedia.",
    "applicant.paymentHintRejected": "Bayaran tidak tersedia untuk permohonan yang tidak diluluskan.",
    "applicant.paymentHintReceiptRejected": "Resit sebelum ini ditolak. Sila muat naik resit baharu untuk pengesahan semula.",
    "applicant.paymentHintSubmitted": "Resit bayaran telah dihantar dan sedang menunggu pengesahan ALiS.",
    "applicant.paymentHintVerified": "Bayaran telah disahkan. Pengeluaran e-lesen QR adalah langkah seterusnya.",
    "applicant.paymentHintIssued": "Bayaran selesai dan e-lesen QR sedia dimuat turun.",
    "applicant.paymentHintDefault": "Bayaran dibuka selepas kelulusan dan invois dijana.",
    "steps.applicationSteps": "Langkah Permohonan",
    "steps.stepOf": "Langkah {active} daripada {total}",
    "steps.editing": "Sedang edit",
    "steps.saveFirstStepHint": "Simpan langkah 1 dahulu untuk buka langkah seterusnya.",
    "steps.sittingApplication": "Permohonan Tapak",
    "steps.clientDepartment": "Butiran Jabatan Pelanggan",
    "steps.submittingPerson": "Butiran Orang Yang Mengemukakan",
    "steps.landDetails": "Butiran Tanah",
    "steps.buildingPlan": "Pelan Bangunan Terperinci",
    "steps.proposalAnalysis": "Analisis Cadangan",
    "steps.siteInspection": "Pemeriksaan Tapak",
    "steps.buildingPlanChecklist": "Senarai Semak Pelan Bangunan",
    "steps.printForm": "Cetak Borang",
    "steps.supportingDocument": "Dokumen Sokongan",
    "steps.declaration": "Akuan",
    "decision.notApproved": "Tidak diluluskan",
    "decision.approved": "Diluluskan",
    "decision.waiting": "Menunggu keputusan",
    "decision.rejected": "Ditolak",
    "decision.approvedWithConditions": "Lulus bersyarat",
    "decision.pending": "Belum selesai",
    "decision.referNotice": "Sila rujuk notis ALiS",
    "decision.notificationReceived": "Notifikasi keputusan diterima",
    "status.draft": "Draf",
    "status.incomplete": "Tidak Lengkap",
    "status.submitted": "Dihantar",
    "status.pt_ku_review": "Untuk Semakan PT/KU",
    "status.auto_screened": "Verifikasi S2",
    "status.technical_review": "Semakan Teknikal",
    "status.technical_ku_review": "Semakan Teknikal KU(IKL)",
    "status.technical_review_completed": "Teknikal Selesai",
    "status.management_review": "Perakuan Pengurusan",
    "status.mphlg_processing": "Proses MPHLG",
    "status.mphlg_decision_received": "Keputusan MPHLG Diterima",
    "status.approved": "Diluluskan",
    "status.approved_with_conditions": "Lulus Bersyarat",
    "status.rejected": "Tidak Diluluskan",
    "status.invoice_generated": "Invois Dijana",
    "status.payment_submitted": "Bayaran Dihantar",
    "status.payment_verified": "Bayaran Disahkan",
    "status.license_issued": "E-Lesen Dijana",
    "status.license_revoked": "Lesen Dibatalkan",
  },
  en: {
    ...adminWorkflowEn,
    "app.system": "ALiS System",
    "app.portal": "ALiS Portal",
    "app.license": "Digital Advertisement License",
    "app.workflow": "MPHLG Approval Workflow",
    "common.language": "Language",
    "common.malay": "BM",
    "common.english": "EN",
    "common.logout": "Logout",
    "common.notifications": "Notifications",
    "common.latestUpdates": "Latest ALiS updates",
    "common.new": "New",
    "common.noNotifications": "No notifications",
    "common.markAllRead": "Mark all as read",
    "common.viewAll": "View all",
    "common.help": "Help",
    "common.and": "and",
    "common.loading": "Loading...",
    "common.loadingSelectedApplication": "Loading selected application...",
    "common.reset": "Reset",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.submit": "Submit",
    "common.submitting": "Submitting...",
    "common.signIn": "Sign In",
    "common.signingIn": "Signing in...",
    "common.registerNow": "Register Now",
    "common.newApplication": "New Application",
    "common.continue": "Continue",
    "common.view": "View",
    "common.manage": "Manage",
    "common.download": "Download",
    "common.delete": "Delete",
    "common.ready": "Ready",
    "common.waiting": "Waiting",
    "common.complete": "Complete",
    "common.notComplete": "Not complete",
    "common.pending": "Pending",
    "common.done": "Done",
    "common.search": "Search",
    "common.searchAndFilter": "Search & Filter",
    "common.keyword": "Keyword",
    "common.month": "Month",
    "common.year": "Year",
    "common.allMonths": "All Months",
    "common.allYears": "All Years",
    "common.clearFilters": "Clear Filters",
    "common.status": "Status",
    "common.allStatuses": "All statuses",
    "common.total": "Total",
    "common.drafts": "Drafts",
    "common.submitted": "Submitted",
    "common.paymentAction": "Payment Proof",
    "common.eLicenses": "E-Licenses",
    "common.reference": "Reference",
    "common.project": "Project",
    "common.type": "Type",
    "common.department": "Department",
    "common.updated": "Updated",
    "common.action": "Action",
    "common.open": "Open",
    "common.invoice": "Invoice",
    "common.amount": "Amount",
    "common.paymentStatus": "Payment Status",
    "common.receiptReference": "Receipt Reference",
    "common.receipt": "Receipt",
    "common.uploadReceipt": "Upload Receipt",
    "common.application": "Application",
    "common.applicant": "Applicant",
    "common.lastUpdated": "Last updated",
    "common.notification": "Notification",
    "common.copyright": "© 2026 Advertisement License Application. All Rights Reserved.",
    "notifications.eyebrow": "Live Notification Center",
    "notifications.title": "Notifications",
    "notifications.description": "Live alerts generated from application status, workflow decisions, payment, and QR e-license records.",
    "notifications.refresh": "Refresh",
    "notifications.unread": "Unread",
    "notifications.actionRequired": "Action Required",
    "notifications.licensePayment": "Payment / License",
    "notifications.inbox": "Inbox",
    "notifications.lastSynced": "Last synced",
    "notifications.waitingForSync": "Waiting for live sync.",
    "notifications.liveInbox": "Live Inbox",
    "notifications.records": "record(s)",
    "notifications.emptyDescription": "Notifications will appear here when an application needs action or changes status.",
    "notifications.markRead": "Mark Read",
    "notifications.openRecord": "View",
    "notifications.filter.all": "All",
    "notifications.filter.unread": "Unread",
    "notifications.filter.account": "Account",
    "notifications.filter.screening": "Screening",
    "notifications.filter.technical": "Technical",
    "notifications.filter.approval": "Approval",
    "notifications.filter.payment": "Payment",
    "notifications.filter.license": "License",
    "notifications.filter.correction": "Correction",
    "notifications.filter.decision": "Decision",
    "notifications.filter.progress": "Progress",
    "common.nextStep": "Next step",
    "common.decision": "Decision",
    "common.remark": "Remark",
    "common.date": "Date",
    "common.currentPhase": "Current Phase",
    "app.digitalLicenseSystem": "Digital License System",
    "app.advertisementLicenseApplication": "Advertisement License Application",
    "app.digitalLicensePortal": "Advertisement License Application",
    "app.digitalAdvertisementLicense": "Digital Advertisement License",
    "app.digitalAdvertisementLicenseSystem": "Advertisement License Application",
    "app.authFeatureSubmit": "Online Submission of Advertisement Applications and Supporting Documents.",
    "app.authFeatureTrack": "Application Status Tracking",
    "role.admin": "Administrator",
    "role.officer": "ALiS Officer",
    "role.applicant": "Applicant",
    "role.officerPortal": "Officer Portal",
    "role.applicantPortal": "Applicant Portal",
    "role.ALiSUser": "ALiS User",
    "profile.welcome": "Welcome",
    "profile.profile": "Profile",
    "profile.accountProfile": "Account Profile",
    "profile.accountRegistrationInfo": "Information from your account registration.",
    "profile.backToDashboard": "Back to Dashboard",
    "profile.leavePasswordBlank": "Leave blank if you do not want to change password",
    "profile.saveSuccess": "Profile details updated successfully.",
    "profile.saveFailed": "Profile details could not be updated.",
    "nav.overview": "Overview",
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "superadmin.nav.users": "User",
    "superadmin.nav.admins": "Admin",
    "nav.myDashboard": "My Dashboard",
    "nav.applicationFlow": "Application Flow",
    "nav.applications": "Applications",
    "nav.guidelines": "Guidelines",
    "nav.myApplications": "My Applications",
    "nav.verification": "S2 Verification",
    "nav.technical": "Technical",
    "nav.approval": "Approval",
    "nav.payment": "Payment",
    "nav.license": "E-License / QR",
    "nav.enforcement": "Enforcement",
    "nav.reports": "Reports",
    "nav.notifications": "Notifications",
    "dashboard.eyebrow": "ALiS System",
    "dashboard.title": "Advertisement License Dashboard",
    "dashboard.description":
      "Monitor digital advertisement license applications against the 25-day target: registration, verification, technical review, management recommendation, MPHLG, approval, payment, and e-license.",
    "dashboard.total": "Total Applications",
    "dashboard.totalNote": "All advertisement license applications",
    "dashboard.underReview": "Under Review",
    "dashboard.underReviewNote": "Waiting for licensing or technical action",
    "dashboard.pendingPayment": "Pending Payment",
    "dashboard.pendingPaymentNote": "Approved but payment not completed",
    "dashboard.licensesIssued": "Licenses Issued",
    "dashboard.licensesIssuedNote": "Active digital licenses",
    "dashboard.statusSummary": "Application Status Summary",
    "dashboard.statusSummaryDesc": "Total applications by flowchart phase.",
    "dashboard.sla": "SLA Monitoring",
    "dashboard.slaDesc": "The system-wide target is 25 days.",
    "dashboard.recent": "Recent Applications",
    "dashboard.recentDesc": "Advertisement license applications received or currently being processed.",
    "dashboard.flow": "System Flowchart",
    "dashboard.flowDesc": "Digital advertisement license process sequence based on the MPHLG chart.",
    "dashboard.departmentPerformance": "Department / Agency Performance",
    "dashboard.departmentDesc": "Monitor assigned, pending, and completed actions by role.",
    "auth.loginTitle": "Sign In",
    "auth.welcome": "Welcome",
    "auth.loginDescription": "Access your personal dashboard and services.",
    "auth.malaysian": "Malaysian",
    "auth.icNumber": "IC Number",
    "auth.loginIdentifier": "IC Number / Admin ID",
    "auth.emailAddress": "Email Address",
    "auth.password": "Password",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot Password?",
    "auth.reset.eyebrow": "Account Recovery",
    "auth.reset.title": "Reset your password",
    "auth.reset.description": "Enter your registered email, choose how to receive the OTP, then create a new password after verification.",
    "auth.reset.stepEmail": "Email",
    "auth.reset.stepWhatsapp": "WhatsApp",
    "auth.reset.stepOtp": "OTP",
    "auth.reset.stepPassword": "Password",
    "auth.reset.emailPlaceholder": "e.g. name@email.com",
    "auth.reset.whatsappNumber": "WhatsApp Number",
    "auth.reset.whatsappPlaceholder": "e.g. 60123456789",
    "auth.reset.chooseChannel": "Receive OTP by",
    "auth.reset.channelEmail": "Email",
    "auth.reset.channelEmailDesc": "Send the OTP to your registered email.",
    "auth.reset.channelWhatsapp": "WhatsApp",
    "auth.reset.channelWhatsappDesc": "Send the OTP to your registered phone number.",
    "auth.reset.getOtp": "Get OTP",
    "auth.reset.sendingOtp": "Sending OTP...",
    "auth.reset.otpSent": "OTP sent. Please check your selected channel.",
    "auth.reset.devOtp": "Development OTP",
    "auth.reset.enterOtp": "Enter the 6-digit OTP",
    "auth.reset.otpDigit": "OTP digit",
    "auth.reset.otpHint": "The OTP expires in 10 minutes. Do not share this OTP with anyone.",
    "auth.reset.enterCompleteOtp": "Please enter all 6 OTP digits.",
    "auth.reset.verifyOtp": "Verify OTP",
    "auth.reset.verifying": "Verifying OTP...",
    "auth.reset.resendOtp": "Resend OTP",
    "auth.reset.otpVerified": "OTP verified. Please create a new password.",
    "auth.reset.newPassword": "New Password",
    "auth.reset.savePassword": "Save New Password",
    "auth.reset.passwordMin": "Password must be at least 8 characters long.",
    "auth.reset.successLogin": "Password reset successful. Please login with your new password.",
    "auth.reset.checkEmail": "Please check the email address you entered.",
    "auth.reset.checkWhatsapp": "Please check the WhatsApp number you entered.",
    "auth.reset.validationWhatsapp": "Please enter your registered WhatsApp number.",
    "auth.reset.validationWhatsappFormat": "Please enter a valid WhatsApp number.",
    "auth.reset.errorGeneric": "We could not process this request right now. Please try again.",
    "auth.reset.errorNotFound": "No ALiS account was found for that email address.",
    "auth.reset.errorNotFoundWhatsapp": "No ALiS account was found for that WhatsApp number.",
    "auth.reset.errorExpired": "The OTP or reset session has expired. Please request a new OTP.",
    "auth.reset.errorTooMany": "Too many incorrect OTP attempts. Please request a new OTP.",
    "auth.reset.errorNoWhatsapp": "This account does not have a registered WhatsApp/mobile number. Please choose email.",
    "auth.reset.errorNoEmail": "This account does not have a registered email address.",
    "auth.noAccount": "Don't have an account?",
    "auth.enterIcPassword": "Please enter IC Number and password.",
    "auth.validation.loginIc": "Please enter your IC Number.",
    "auth.validation.loginIdentifier": "Please enter your IC Number or Admin ID.",
    "auth.validation.loginPassword": "Please enter your password.",
    "auth.validation.loginMykadFormat": "IC Number must contain 12 digits without dashes.",
    "auth.validation.loginIdentifierFormat": "Please enter a valid 12-digit IC Number or Admin ID.",
    "auth.enterEmailPassword": "Please enter email and password.",
    "auth.loginIcFailed": "Wrong credentials. Please check your IC Number and password.",
    "auth.loginEmailFailed": "Login failed. Please check your email and password.",
    "auth.registrationTitle": "Account Registration",
    "auth.registrationMalaysianDescription": "Complete the form below to create your account. Ensure all information matches your official identification documents.",
    "auth.personalInformation": "Personal Information",
    "auth.fullNameMyKad": "Full Name (as per MyKad)",
    "auth.fullNamePlaceholder": "Enter your full legal name",
    "auth.gender": "Gender",
    "auth.selectGender": "Select gender",
    "auth.genderMale": "Male",
    "auth.genderFemale": "Female",
    "auth.dateOfBirth": "Date of Birth",
    "auth.nationality": "Nationality",
    "auth.mykadNumber": "MyKad Number",
    "auth.enterWithoutDashes": "Enter without dashes",
    "auth.contactDetails": "Contact Details",
    "auth.mobileNumber": "Mobile Number",
    "auth.address": "Address",
    "auth.addressLine1": "Unit / Floor / Block",
    "auth.addressLine2": "Street & Residential Area",
    "auth.addressLine1Placeholder": "e.g. Unit 3A, Floor 2, Block B",
    "auth.addressLine2Placeholder": "e.g. Jalan Satok, Taman Satok",
    "auth.postcode": "Postcode",
    "auth.city": "City",
    "auth.selectCity": "Select city",
    "auth.selectStateFirst": "Select state first",
    "auth.state": "State",
    "auth.selectState": "Select state",
    "auth.accountSecurity": "Account Security",
    "auth.retypePassword": "Retype Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.captchaVerification": "Captcha Verification",
    "auth.notRobot": "I'm not a robot",
    "auth.verification": "Verification",
    "auth.privacyTerms": "Privacy - Terms",
    "auth.localCaptchaPreview": "Local preview only. Add a Google reCAPTCHA site key to show the real widget.",
    "auth.submitRegistration": "Submit Registration",
    "auth.backToLogin": "Back to Login",
    "auth.registerSuccess": "Registration successful. Please login to continue.",
    "auth.registerSuccessLogin": "Account registration successful. Please login using the IC Number and password you registered.",
    "auth.registerFailed": "Registration failed. Please check your information.",
    "auth.recaptchaLoadFailed": "reCAPTCHA could not load. Please try again.",
    "auth.recaptchaConnectionFailed": "reCAPTCHA could not load. Please check your connection.",
    "auth.validation.fullName": "Please enter your full name.",
    "auth.validation.summary": "Please check the highlighted fields and complete the required information.",
    "auth.validation.gender": "Please select your gender.",
    "auth.validation.dateOfBirth": "Please enter your date of birth.",
    "auth.validation.nationality": "Please enter your nationality.",
    "auth.validation.mykad": "Please enter your MyKad Number.",
    "auth.validation.mykadFormat": "MyKad Number must contain 12 digits without dashes.",
    "auth.validation.mobile": "Please enter your mobile number.",
    "auth.validation.email": "Please enter your email address.",
    "auth.validation.emailFormat": "Please enter a valid email address.",
    "auth.validation.mykadExists": "This MyKad Number is already registered. Please login or use another MyKad Number.",
    "auth.validation.emailExists": "This email address is already registered. Please use another email address.",
    "auth.validation.addressLine1": "Please enter your unit, floor or block.",
    "auth.validation.addressLine2": "Please enter your street and residential area.",
    "auth.validation.addressLine1Length": "Unit / Floor / Block must be 150 characters or fewer.",
    "auth.validation.addressLine2Length": "Street & Residential Area must be 150 characters or fewer.",
    "auth.validation.postcode": "Please enter your postcode.",
    "auth.validation.city": "Please enter your city.",
    "auth.validation.state": "Please enter your state.",
    "auth.validation.password": "Please enter your password.",
    "auth.validation.confirmPassword": "Please retype your password.",
    "auth.validation.passwordMismatch": "Password and Confirm Password do not match.",
    "auth.validation.recaptcha": "Please complete the reCAPTCHA verification.",
    "auth.validation.captcha": "Please complete the captcha verification.",
    "auth.validation.recaptchaFailed": "reCAPTCHA verification failed. Please try again.",
    "auth.copyright": "All Rights Reserved.",
    "auth.termsService": "Terms of Service",
    "auth.faq": "FAQ",
    "auth.contactUs": "Contact Us",
    "faq.title": "Frequently Asked Questions (FAQ)",
    "faq.description": "Quick answers to help you use the ALiS advertisement license application portal.",
    "faq.createApplication.question": "How do I create a new application?",
    "faq.createApplication.answer": "After logging in, click the Submit New Application button on your dashboard and fill in all required fields. Upload all necessary documents and submit the application.",
    "faq.rejected.question": "What should I do if my application is rejected?",
    "faq.rejected.answer": "Check the remarks provided with the rejection notification. Correct the highlighted issues in your application and resubmit.",
    "faq.payment.question": "How do I make the payment?",
    "faq.payment.answer": "Once your application is approved, you will receive a bill. You can make the payment via online banking or cash at the designated counter. After paying, upload your payment proof in the portal.",
    "faq.renewLicense.question": "How do I renew my license?",
    "faq.renewLicense.answer": "You will receive renewal reminders before your license expires. Follow the instructions in the reminder to submit renewal application and payment.",
    "faq.contactHelp.question": "Who can I contact for help?",
    "faq.contactHelp.answer": "For assistance, please email support@example.com or call +60 123 456 789 during office hours.",
    "applicant.portal": "Applicant Portal",
    "applicant.records": "Applicant Records",
    "applicant.dashboardTitle": "My Advertisement License Applications",
    "applicant.dashboardDescription": "Start an online application, upload documents, track status in real time, receive decisions, complete payment, and download your QR e-license.",
    "applicant.applicationsTitle": "My Applications",
    "applicant.applicationsDescription": "Track every application from draft to S2 verification, technical review, approval, payment, and QR e-license.",
    "applicant.workspaceTitle": "Application Workspace",
    "applicant.totalApplications": "Total Applications",
    "applicant.currentProgress": "Current Progress",
    "applicant.statusTrackingDescription": "Track every submitted application from review through decision, payment, and e-license.",
    "applicant.noApplicationSubmitted": "No application submitted yet.",
    "applicant.createApplicationHint": "Create a new application to start the registration phase.",
    "applicant.flowTitle": "Applicant (Front-End Module)",
    "applicant.flowDescription": "Complete applicant flow after login based on the digital advertisement license chart.",
    "applicant.startTitle": "Start",
    "applicant.startDesc": "Applicant enters the portal.",
    "applicant.s1Title": "Access Portal & Login",
    "applicant.s1Desc": "Applicant dashboard and active account.",
    "applicant.formUploadTitle": "Complete Form & Upload Documents",
    "applicant.formUploadDesc": "Complete 11 steps and supporting documents.",
    "applicant.statusCompleteTitle": "Status Complete?",
    "applicant.correctionEmailDesc": "Correction action through email.",
    "applicant.memoDesc": "If complete, an internal memo is generated.",
    "applicant.memoTitle": "Status 'Complete', Generate Internal Memo",
    "applicant.memoMoveDesc": "Application moves to the Licensing Division.",
    "applicant.decisionNoticeTitle": "Receive Decision Notification",
    "applicant.decisionNoticeDesc": "Notice of approved, conditional approval, or not approved.",
    "applicant.onlinePaymentTitle": "Upload Payment Receipt",
    "applicant.onlinePaymentDesc": "Upload the payment receipt after the invoice is generated.",
    "applicant.licenseDownloadTitle": "Download E-License (QR Code)",
    "applicant.licenseDownloadDesc": "QR e-license can be downloaded after the license is issued.",
    "applicant.endTitle": "End",
    "applicant.endDesc": "Applicant flow completed.",
    "applicant.applicationSelected": "Application selected",
    "applicant.noApplicationYet": "No application yet",
    "applicant.startRequired": "Start required",
    "applicant.dashboardHeaderTitle": "Dashboard",
    "applicant.dashboardHeaderDescription": "Review your next action, prepare application details, and monitor your advertisement license matters.",
    "applicant.statusCorrection": "N: Correction",
    "applicant.statusCompleteYes": "Y: Complete",
    "applicant.actionsTitle": "Applicant Actions",
    "applicant.actionsDescription": "Complete the front-end applicant actions from application, correction, decision notification, payment, to QR e-license.",
    "applicant.actionsEmptyDescription": "Create a new application to activate applicant actions.",
    "applicant.s1ActionTitle": "Access portal, login, complete form, and upload documents",
    "applicant.actionRequired": "Action required",
    "applicant.completed": "Completed",
    "applicant.continueApplication": "Continue Application",
    "applicant.viewSubmission": "View Submission",
    "applicant.correctionTitle": "Receive correction notification and update incomplete information",
    "applicant.correctionRequired": "Correction required",
    "applicant.noCorrectionRequest": "No correction request",
    "applicant.emailCorrectionRequested": "Email correction requested",
    "applicant.noActiveCorrectionNotice": "No active correction notice",
    "applicant.updateApplicationForm": "Update the application form",
    "applicant.waitLicensingReview": "Wait for licensing review",
    "applicant.openCorrection": "Open Correction",
    "applicant.receiveDecisionTitle": "Receive decision notification from the approval stage",
    "applicant.paymentByFpxCard": "Upload payment receipt",
    "applicant.waitingInvoice": "Waiting for invoice",
    "applicant.notSubmitted": "Not submitted",
    "applicant.submitPayment": "Submit Receipt",
    "applicant.selectedApplication": "Selected Application",
    "applicant.downloadQrELicense": "Download QR E-License",
    "applicant.qrLicensePending": "QR e-license will appear after payment has been verified and the license is issued.",
    "applicant.workflowInactive": "No applicant workflow is active yet.",
    "applicant.overviewTitle": "Dashboard Overview",
    "applicant.overviewDescription": "Review your application summary, next actions, submitted status, and e-licenses from one place.",
    "applicant.latestActivity": "Latest Activity",
    "applicant.dashboardEmptyOverview": "No application activity yet. Start a new application to see progress and status here.",
    "applicant.nextActionStartTitle": "Start your advertisement license application",
    "applicant.nextActionStartDescription": "Prepare your project information, submitting person details, and supporting documents before sending the application to ALiS.",
    "applicant.nextActionDraftTitle": "Continue your draft application",
    "applicant.nextActionDraftDescription": "Resume the incomplete application step and submit once all details and documents are ready.",
    "applicant.nextActionSubmittedTitle": "Monitor your application progress",
    "applicant.nextActionSubmittedDescription": "Your application is recorded. Check status, decisions, payment, and e-license updates from this portal.",
    "applicant.beforeApplyTitle": "Before You Apply",
    "applicant.beforeApplyDescription": "Keep these key details ready so the application process is smoother.",
    "applicant.dashboardChecklistProject": "Project details and advertisement site location",
    "applicant.dashboardChecklistPerson": "Submitting person details and contact number",
    "applicant.dashboardChecklistDocuments": "Supporting documents ready for upload",
    "applicant.dashboardChecklistDeclaration": "Final review before declaration and form printout",
    "applicant.calendarTitle": "Calendar",
    "applicant.calendarActivityHint": "Green dots mark dates with application activity.",
    "applicant.calendarEmptyHint": "Application activity will be marked here once records are created.",
    "applicant.applicationJourneyTitle": "Application Journey",
    "applicant.applicationJourneyDescription": "Complete these steps before the application is submitted for review.",
    "applicant.myApplicationsDesc": "A clean list of your draft and submitted records.",
    "applicant.applicationsSectionTitle": "Applications",
    "applicant.applicationsSectionDescription": "Create a new application, continue drafts, search records, and manage your advertisement license submissions.",
    "applicant.statusSectionTitle": "Application Status",
    "applicant.licenseSectionTitle": "E-Licenses and Payment Proof",
    "applicant.licenseSectionDescription": "Upload payment proof, check payment verification, and download your QR e-license when it is ready.",
    "applicant.tabApplications": "Applications",
    "applicant.tabStatus": "Status",
    "applicant.tabPayment": "Payment",
    "applicant.tabLicense": "E-Licenses",
    "applicant.paymentProofTitle": "Payment Proof",
    "applicant.noApplicationsYet": "No applications yet.",
    "applicant.searchPlaceholder": "Search reference, project, type, or status",
    "applicant.searchFilterHint": "Filter records by keyword, application month, and application year.",
    "applicant.applicationList": "Application List",
    "applicant.recordsFound": "record(s) found.",
    "applicant.submittedApplications": "submitted application(s)",
    "applicant.noUserApplications": "You have no applications yet.",
    "applicant.paymentSubmittedSuccess": "Payment receipt submitted. ALiS will verify it before the QR e-license is issued.",
    "applicant.paymentSubmissionFailed": "Payment submission failed.",
    "applicant.receiptUploadRequired": "Please upload the payment receipt before submitting.",
    "applicant.receiptUploadFailed": "Receipt upload failed.",
    "applicant.chooseReceiptFile": "Choose receipt file",
    "applicant.receiptUploadHint": "PDF or image accepted as payment proof.",
    "applicant.detailsLoadFailed": "Unable to load selected application details.",
    "applicant.paymentHintDraft": "Complete and submit the application before payment is available.",
    "applicant.paymentHintRejected": "Payment is not available for rejected applications.",
    "applicant.paymentHintReceiptRejected": "The previous receipt was rejected. Please upload a new receipt for re-verification.",
    "applicant.paymentHintSubmitted": "Payment receipt has been submitted and is waiting for ALiS verification.",
    "applicant.paymentHintVerified": "Payment has been verified. QR e-license issuance is next.",
    "applicant.paymentHintIssued": "Payment is complete and QR e-license is ready to download.",
    "applicant.paymentHintDefault": "Payment opens after approval and invoice generation.",
    "steps.applicationSteps": "Application Steps",
    "steps.stepOf": "Step {active} of {total}",
    "steps.editing": "Editing",
    "steps.saveFirstStepHint": "Save step 1 first to unlock the next steps.",
    "steps.sittingApplication": "Sitting Application",
    "steps.clientDepartment": "Details of Client Department",
    "steps.submittingPerson": "Details of Submitting Person",
    "steps.landDetails": "Details of Land(s)",
    "steps.buildingPlan": "Detailed Building Plan",
    "steps.proposalAnalysis": "Analysis of Proposal",
    "steps.siteInspection": "Site Inspection",
    "steps.buildingPlanChecklist": "Building Plan Checklist",
    "steps.printForm": "Print Form",
    "steps.supportingDocument": "Supporting Document",
    "steps.declaration": "Declaration",
    "decision.notApproved": "Not approved",
    "decision.approved": "Approved",
    "decision.waiting": "Waiting for decision",
    "decision.rejected": "Rejected",
    "decision.approvedWithConditions": "Approved with conditions",
    "decision.pending": "Pending",
    "decision.referNotice": "Please refer to ALiS notice",
    "decision.notificationReceived": "Decision notification received",
    "status.draft": "Draft",
    "status.incomplete": "Incomplete",
    "status.submitted": "Submitted",
    "status.pt_ku_review": "For PT/KU Review",
    "status.auto_screened": "S2 Verification",
    "status.technical_review": "Technical Review",
    "status.technical_ku_review": "KU(IKL) Technical Review",
    "status.technical_review_completed": "Technical Completed",
    "status.management_review": "Management Recommendation",
    "status.mphlg_processing": "MPHLG Processing",
    "status.mphlg_decision_received": "MPHLG Decision Received",
    "status.approved": "Approved",
    "status.approved_with_conditions": "Approved with Conditions",
    "status.rejected": "Rejected",
    "status.invoice_generated": "Invoice Generated",
    "status.payment_submitted": "Payment Submitted",
    "status.payment_verified": "Payment Verified",
    "status.license_issued": "E-License Generated",
    "status.license_revoked": "License Revoked",
  },
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
  if (typeof window === "undefined") return "en";

  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "en" || stored === "ms" ? stored : "en";
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(getInitialLanguage);

  useEffect(() => {
    document.documentElement.lang = language === "ms" ? "ms-MY" : "en";
  }, [language]);

  function setLanguage(nextLanguage) {
    const normalized = nextLanguage === "en" ? "en" : "ms";
    setLanguageState(normalized);
    localStorage.setItem(STORAGE_KEY, normalized);
    document.documentElement.lang = normalized === "ms" ? "ms-MY" : "en";
  }

  const value = useMemo(() => {
    function t(key, fallback) {
      return (
        dictionaries[language]?.[key] ||
        dictionaries.en[key] ||
        fallback ||
        key
      );
    }

    return {
      language,
      setLanguage,
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}
