/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "fastrack_language";

const dictionaries = {
  ms: {
    "app.system": "Sistem fasTrack",
    "app.portal": "Portal fasTrack",
    "app.license": "Lesen Iklan Digital",
    "app.workflow": "Aliran Kelulusan MPHLG",
    "common.language": "Bahasa",
    "common.malay": "BM",
    "common.english": "EN",
    "common.logout": "Log Keluar",
    "common.notifications": "Notifikasi",
    "common.latestUpdates": "Kemas kini fasTrack terkini",
    "common.new": "Baharu",
    "common.noNotifications": "Tiada notifikasi",
    "common.markAllRead": "Tanda semua dibaca",
    "common.viewAll": "Lihat semua",
    "common.help": "Bantuan",
    "common.and": "dan",
    "common.loading": "Memuatkan...",
    "common.loadingSelectedApplication": "Memuatkan permohonan dipilih...",
    "common.reset": "Set Semula",
    "common.submit": "Hantar",
    "common.submitting": "Menghantar...",
    "common.signIn": "Log Masuk",
    "common.signingIn": "Sedang log masuk...",
    "common.registerNow": "Daftar Sekarang",
    "common.newApplication": "Permohonan Baharu",
    "common.continue": "Teruskan",
    "common.view": "Lihat",
    "common.manage": "Urus",
    "common.download": "Muat Turun",
    "common.ready": "Sedia",
    "common.waiting": "Menunggu",
    "common.complete": "Selesai",
    "common.notComplete": "Belum selesai",
    "common.pending": "Belum selesai",
    "common.done": "Selesai",
    "common.search": "Carian",
    "common.keyword": "Kata Kunci",
    "common.status": "Status",
    "common.allStatuses": "Semua status",
    "common.total": "Jumlah",
    "common.drafts": "Draf",
    "common.submitted": "Dihantar",
    "common.paymentAction": "Tindakan Bayaran",
    "common.eLicenses": "E-Lesen",
    "common.reference": "Rujukan",
    "common.project": "Projek",
    "common.type": "Jenis",
    "common.updated": "Dikemas Kini",
    "common.action": "Tindakan",
    "common.invoice": "Invois",
    "common.amount": "Amaun",
    "common.paymentStatus": "Status Bayaran",
    "common.receiptReference": "Rujukan Resit",
    "common.paymentMethod": "Kaedah Bayaran",
    "common.application": "Permohonan",
    "common.applicant": "Pemohon",
    "common.lastUpdated": "Terakhir dikemas kini",
    "common.notification": "Notifikasi",
    "common.nextStep": "Langkah seterusnya",
    "common.decision": "Keputusan",
    "common.remark": "Catatan",
    "common.date": "Tarikh",
    "common.currentPhase": "Fasa Semasa",
    "app.digitalLicenseSystem": "Sistem Lesen Digital",
    "app.digitalLicensePortal": "Portal Lesen Digital",
    "app.digitalAdvertisementLicense": "Lesen Iklan Digital",
    "app.digitalAdvertisementLicenseSystem": "Sistem Lesen Iklan Digital",
    "app.authFeatureSubmit": "Hantar permohonan dan dokumen secara dalam talian",
    "app.authFeatureTrack": "Jejak verifikasi S2, semakan teknikal dan kelulusan",
    "app.authFeatureComplete": "Selesaikan bayaran dan terima e-lesen QR",
    "role.admin": "Pentadbir",
    "role.officer": "Pegawai DBKU",
    "role.applicant": "Pemohon",
    "role.officerPortal": "Portal Pegawai",
    "role.applicantPortal": "Portal Pemohon",
    "role.fasTrackUser": "Pengguna fasTrack",
    "nav.overview": "Gambaran",
    "nav.home": "Laman Utama",
    "nav.dashboard": "Papan Pemuka",
    "nav.myDashboard": "Papan Pemuka Saya",
    "nav.applicationFlow": "Aliran Permohonan",
    "nav.applications": "Permohonan",
    "nav.myApplications": "Permohonan Saya",
    "nav.verification": "Verifikasi S2",
    "nav.technical": "Teknikal",
    "nav.approval": "Kelulusan",
    "nav.payment": "Bayaran",
    "nav.license": "E-Lesen / QR",
    "nav.enforcement": "Penguatkuasaan",
    "nav.reports": "Laporan",
    "nav.notifications": "Notifikasi",
    "dashboard.eyebrow": "Sistem fasTrack",
    "dashboard.title": "Papan Pemuka Lesen Iklan",
    "dashboard.description":
      "Pantau permohonan lesen iklan digital mengikut sasaran 25 hari: pendaftaran, verifikasi, teknikal, perakuan, MPHLG, kelulusan, bayaran dan e-lesen.",
    "dashboard.total": "Jumlah Permohonan",
    "dashboard.totalNote": "Semua permohonan lesen iklan",
    "dashboard.underReview": "Dalam Semakan",
    "dashboard.underReviewNote": "Menunggu tindakan bahagian lesen atau teknikal",
    "dashboard.pendingPayment": "Menunggu Bayaran",
    "dashboard.pendingPaymentNote": "Diluluskan tetapi bayaran belum selesai",
    "dashboard.licensesIssued": "Lesen Dikeluarkan",
    "dashboard.licensesIssuedNote": "E-lesen aktif",
    "dashboard.statusSummary": "Ringkasan Status Permohonan",
    "dashboard.statusSummaryDesc": "Jumlah permohonan mengikut fasa carta alir.",
    "dashboard.sla": "Pemantauan SLA",
    "dashboard.slaDesc": "Sasaran keseluruhan sistem ialah 25 hari.",
    "dashboard.recent": "Permohonan Terkini",
    "dashboard.recentDesc": "Permohonan lesen iklan yang diterima atau sedang diproses.",
    "dashboard.flow": "Carta Alir Sistem",
    "dashboard.flowDesc": "Urutan proses lesen iklan digital seperti carta MPHLG.",
    "dashboard.departmentPerformance": "Prestasi Bahagian / Agensi",
    "dashboard.departmentDesc": "Pantau tugasan, tindakan tertunggak dan selesai mengikut peranan.",
    "auth.loginTitle": "Log Masuk",
    "auth.loginDescription": "Akses papan pemuka dan perkhidmatan anda.",
    "auth.malaysian": "Warganegara Malaysia",
    "auth.nonMalaysian": "Bukan Warganegara",
    "auth.icNumber": "Nombor MyKad",
    "auth.emailAddress": "Alamat E-mel",
    "auth.password": "Kata Laluan",
    "auth.rememberMe": "Ingat saya",
    "auth.forgotPassword": "Lupa Kata Laluan?",
    "auth.noAccount": "Belum ada akaun?",
    "auth.enterIcPassword": "Sila masukkan Nombor MyKad dan kata laluan.",
    "auth.enterEmailPassword": "Sila masukkan e-mel dan kata laluan.",
    "auth.loginIcFailed": "Log masuk gagal. Sila semak Nombor MyKad dan kata laluan anda.",
    "auth.loginEmailFailed": "Log masuk gagal. Sila semak e-mel dan kata laluan anda.",
    "auth.registrationTitle": "Pendaftaran Akaun",
    "auth.registrationMalaysianDescription": "Lengkapkan borang di bawah untuk mencipta akaun anda. Pastikan semua maklumat sepadan dengan dokumen pengenalan rasmi anda.",
    "auth.registrationNonMalaysianDescription": "Lengkapkan borang di bawah untuk mencipta akaun anda. Pastikan semua maklumat sepadan dengan dokumen pasport rasmi anda.",
    "auth.personalInformation": "Maklumat Peribadi",
    "auth.fullNameMyKadPassport": "Nama Penuh (seperti MyKad/Pasport)",
    "auth.fullNamePassport": "Nama Penuh (seperti Pasport)",
    "auth.fullNamePlaceholder": "Masukkan nama penuh rasmi anda",
    "auth.nationality": "Kewarganegaraan",
    "auth.mykadNumber": "Nombor MyKad",
    "auth.enterWithoutDashes": "Masukkan tanpa sengkang",
    "auth.contactDetails": "Butiran Perhubungan",
    "auth.mobileNumber": "Nombor Telefon Bimbit",
    "auth.residentialAddress": "Alamat Kediaman",
    "auth.addressPlaceholder": "Masukkan alamat surat-menyurat penuh anda",
    "auth.accountSecurity": "Keselamatan Akaun",
    "auth.retypePassword": "Taip Semula Kata Laluan",
    "auth.secureWordHint": "Kata Selamat digunakan untuk mengesahkan ketulenan portal semasa log masuk. Jangan masukkan kata laluan jika kata selamat yang dipaparkan tidak sepadan.",
    "auth.secureWord": "Kata Selamat",
    "auth.agreePrefix": "Saya telah bersetuju dengan",
    "auth.terms": "Terma dan Syarat",
    "auth.privacy": "Polisi Privasi",
    "auth.agreeSuffix": "yang mengawal penggunaan Portal DBKU.",
    "auth.submitRegistration": "Hantar Pendaftaran",
    "auth.backToLogin": "Kembali ke Log Masuk",
    "auth.passportNumber": "Nombor Pasport",
    "auth.passportPlaceholder": "Masukkan nombor pasport anda",
    "auth.countryOfOrigin": "Negara Asal",
    "auth.selectCountry": "Pilih negara anda",
    "auth.passportExpiryDate": "Tarikh Tamat Pasport",
    "auth.copyright": "Hak Cipta Terpelihara.",
    "auth.termsService": "Terma Perkhidmatan",
    "auth.faq": "Soalan Lazim",
    "auth.contactUs": "Hubungi Kami",
    "applicant.portal": "Portal Pemohon",
    "applicant.records": "Rekod Pemohon",
    "applicant.dashboardTitle": "Permohonan Lesen Iklan Saya",
    "applicant.dashboardDescription": "Mulakan permohonan dalam talian, muat naik dokumen, jejak status secara masa nyata, terima keputusan, selesaikan bayaran dan muat turun e-lesen QR.",
    "applicant.applicationsTitle": "Permohonan Saya",
    "applicant.applicationsDescription": "Jejak setiap permohonan daripada draf hingga verifikasi S2, semakan teknikal, kelulusan, bayaran dan e-lesen QR.",
    "applicant.currentProgress": "Kemajuan Semasa",
    "applicant.noApplicationSubmitted": "Belum ada permohonan dihantar.",
    "applicant.createApplicationHint": "Cipta permohonan baharu untuk memulakan fasa pendaftaran.",
    "applicant.flowTitle": "Pemohon (Modul Front-End)",
    "applicant.flowDescription": "Aliran lengkap pemohon selepas log masuk mengikut carta lesen iklan digital.",
    "applicant.startTitle": "Mula",
    "applicant.startDesc": "Pemohon masuk ke portal.",
    "applicant.s1Title": "Akses Portal & Log Masuk",
    "applicant.s1Desc": "Papan pemuka pemohon dan akaun aktif.",
    "applicant.formUploadTitle": "Isi Borang & Muat Naik Dokumen",
    "applicant.formUploadDesc": "Lengkapkan 11 langkah dan dokumen sokongan.",
    "applicant.statusCompleteTitle": "Status Lengkap?",
    "applicant.correctionEmailDesc": "Tindakan pembetulan melalui e-mel.",
    "applicant.memoDesc": "Jika lengkap, memo dalaman dijana.",
    "applicant.memoTitle": "Status 'Lengkap', Jana Memo Dalaman",
    "applicant.memoMoveDesc": "Permohonan bergerak ke Bahagian Lesen.",
    "applicant.decisionNoticeTitle": "Terima Notifikasi Keputusan",
    "applicant.decisionNoticeDesc": "Makluman lulus, lulus bersyarat atau tidak lulus.",
    "applicant.onlinePaymentTitle": "Buat Pembayaran Atas Talian",
    "applicant.onlinePaymentDesc": "FPX atau kad selepas invois dijana.",
    "applicant.licenseDownloadTitle": "Muat Turun E-Lesen (Kod QR)",
    "applicant.licenseDownloadDesc": "E-lesen QR boleh dimuat turun selepas lesen dikeluarkan.",
    "applicant.endTitle": "Tamat",
    "applicant.endDesc": "Aliran pemohon selesai.",
    "applicant.applicationSelected": "Permohonan dipilih",
    "applicant.noApplicationYet": "Belum ada permohonan",
    "applicant.startRequired": "Perlu mula",
    "applicant.statusCorrection": "T: Pembetulan",
    "applicant.statusCompleteYes": "Y: Lengkap",
    "applicant.actionsTitle": "Tindakan Pemohon",
    "applicant.actionsDescription": "Lengkapkan tindakan pemohon daripada permohonan, pembetulan, notifikasi keputusan, bayaran hingga e-lesen QR.",
    "applicant.actionsEmptyDescription": "Cipta permohonan baharu untuk mengaktifkan tindakan pemohon.",
    "applicant.s1ActionTitle": "Akses portal, log masuk, lengkapkan borang dan muat naik dokumen",
    "applicant.actionRequired": "Tindakan diperlukan",
    "applicant.completed": "Selesai",
    "applicant.continueApplication": "Teruskan Permohonan",
    "applicant.viewSubmission": "Lihat Hantaran",
    "applicant.correctionTitle": "Terima notifikasi pembetulan dan kemas kini maklumat tidak lengkap",
    "applicant.correctionRequired": "Pembetulan diperlukan",
    "applicant.noCorrectionRequest": "Tiada permintaan pembetulan",
    "applicant.emailCorrectionRequested": "Pembetulan melalui e-mel diminta",
    "applicant.noActiveCorrectionNotice": "Tiada notis pembetulan aktif",
    "applicant.updateApplicationForm": "Kemas kini borang permohonan",
    "applicant.waitLicensingReview": "Tunggu semakan Bahagian Lesen",
    "applicant.openCorrection": "Buka Pembetulan",
    "applicant.receiveDecisionTitle": "Terima notifikasi keputusan daripada fasa kelulusan",
    "applicant.paymentByFpxCard": "Bayaran dalam talian melalui FPX/kad",
    "applicant.waitingInvoice": "Menunggu invois",
    "applicant.notSubmitted": "Belum dihantar",
    "applicant.submitPayment": "Hantar Bayaran",
    "applicant.selectedApplication": "Permohonan Dipilih",
    "applicant.downloadQrELicense": "Muat Turun E-Lesen QR",
    "applicant.qrLicensePending": "E-lesen QR akan dipaparkan selepas bayaran disahkan dan lesen dikeluarkan.",
    "applicant.workflowInactive": "Tiada aliran kerja pemohon aktif lagi.",
    "applicant.myApplicationsDesc": "Senarai bersih rekod draf dan hantaran anda.",
    "applicant.noApplicationsYet": "Belum ada permohonan.",
    "applicant.searchPlaceholder": "Cari rujukan, projek atau jenis",
    "applicant.applicationList": "Senarai Permohonan",
    "applicant.recordsFound": "rekod dijumpai.",
    "applicant.noUserApplications": "Anda belum mempunyai permohonan.",
    "applicant.paymentSubmittedSuccess": "Bayaran telah dihantar. DBKU akan mengesahkannya sebelum e-lesen QR dikeluarkan.",
    "applicant.paymentSubmissionFailed": "Hantaran bayaran gagal.",
    "applicant.detailsLoadFailed": "Tidak dapat memuatkan butiran permohonan dipilih.",
    "applicant.paymentHintDraft": "Lengkapkan dan hantar permohonan sebelum bayaran tersedia.",
    "applicant.paymentHintRejected": "Bayaran tidak tersedia untuk permohonan yang tidak diluluskan.",
    "applicant.paymentHintSubmitted": "Bayaran telah dihantar dan sedang menunggu pengesahan DBKU.",
    "applicant.paymentHintVerified": "Bayaran telah disahkan. Pengeluaran e-lesen QR adalah langkah seterusnya.",
    "applicant.paymentHintIssued": "Bayaran selesai dan e-lesen QR sedia dimuat turun.",
    "applicant.paymentHintDefault": "Bayaran dibuka selepas kelulusan dan invois dijana.",
    "steps.applicationSteps": "Langkah Permohonan",
    "steps.stepOf": "Langkah {active} daripada {total}",
    "steps.editing": "Sedang edit",
    "steps.saveFirstStepHint": "Simpan langkah 1 dahulu untuk buka langkah seterusnya.",
    "steps.sittingApplication": "Permohonan Tapak",
    "steps.clientDepartment": "Butiran Jabatan Pelanggan",
    "steps.submittingPerson": "Butiran Orang Yang Mengemukakan",
    "steps.landDetails": "Butiran Tanah",
    "steps.buildingPlan": "Pelan Bangunan Terperinci",
    "steps.proposalAnalysis": "Analisis Cadangan",
    "steps.siteInspection": "Pemeriksaan Tapak",
    "steps.buildingPlanChecklist": "Senarai Semak Pelan Bangunan",
    "steps.printForm": "Cetak Borang",
    "steps.supportingDocument": "Dokumen Sokongan",
    "steps.declaration": "Akuan",
    "decision.notApproved": "Tidak diluluskan",
    "decision.approved": "Diluluskan",
    "decision.waiting": "Menunggu keputusan",
    "decision.rejected": "Ditolak",
    "decision.approvedWithConditions": "Lulus bersyarat",
    "decision.pending": "Belum selesai",
    "decision.referNotice": "Sila rujuk notis DBKU",
    "decision.notificationReceived": "Notifikasi keputusan diterima",
    "status.draft": "Draf",
    "status.incomplete": "Tidak Lengkap",
    "status.submitted": "Dihantar",
    "status.auto_screened": "Verifikasi S2",
    "status.technical_review": "Semakan Teknikal",
    "status.technical_review_completed": "Teknikal Selesai",
    "status.management_review": "Perakuan Pengurusan",
    "status.mphlg_processing": "Proses MPHLG",
    "status.mphlg_decision_received": "Keputusan MPHLG Diterima",
    "status.approved": "Diluluskan",
    "status.approved_with_conditions": "Lulus Bersyarat",
    "status.rejected": "Tidak Diluluskan",
    "status.invoice_generated": "Invois Dijana",
    "status.payment_submitted": "Bayaran Dihantar",
    "status.payment_verified": "Bayaran Disahkan",
    "status.license_issued": "E-Lesen Dijana",
    "status.license_revoked": "Lesen Dibatalkan",
  },
  en: {
    "app.system": "fasTrack System",
    "app.portal": "fasTrack Portal",
    "app.license": "Digital Advertisement License",
    "app.workflow": "MPHLG Approval Workflow",
    "common.language": "Language",
    "common.malay": "BM",
    "common.english": "EN",
    "common.logout": "Logout",
    "common.notifications": "Notifications",
    "common.latestUpdates": "Latest fasTrack updates",
    "common.new": "New",
    "common.noNotifications": "No notifications",
    "common.markAllRead": "Mark all as read",
    "common.viewAll": "View all",
    "common.help": "Help",
    "common.and": "and",
    "common.loading": "Loading...",
    "common.loadingSelectedApplication": "Loading selected application...",
    "common.reset": "Reset",
    "common.submit": "Submit",
    "common.submitting": "Submitting...",
    "common.signIn": "Sign In",
    "common.signingIn": "Signing in...",
    "common.registerNow": "Register Now",
    "common.newApplication": "New Application",
    "common.continue": "Continue",
    "common.view": "View",
    "common.manage": "Manage",
    "common.download": "Download",
    "common.ready": "Ready",
    "common.waiting": "Waiting",
    "common.complete": "Complete",
    "common.notComplete": "Not complete",
    "common.pending": "Pending",
    "common.done": "Done",
    "common.search": "Search",
    "common.keyword": "Keyword",
    "common.status": "Status",
    "common.allStatuses": "All statuses",
    "common.total": "Total",
    "common.drafts": "Drafts",
    "common.submitted": "Submitted",
    "common.paymentAction": "Payment Action",
    "common.eLicenses": "E-Licenses",
    "common.reference": "Reference",
    "common.project": "Project",
    "common.type": "Type",
    "common.updated": "Updated",
    "common.action": "Action",
    "common.invoice": "Invoice",
    "common.amount": "Amount",
    "common.paymentStatus": "Payment Status",
    "common.receiptReference": "Receipt Reference",
    "common.paymentMethod": "Payment Method",
    "common.application": "Application",
    "common.applicant": "Applicant",
    "common.lastUpdated": "Last updated",
    "common.notification": "Notification",
    "common.nextStep": "Next step",
    "common.decision": "Decision",
    "common.remark": "Remark",
    "common.date": "Date",
    "common.currentPhase": "Current Phase",
    "app.digitalLicenseSystem": "Digital License System",
    "app.digitalLicensePortal": "Digital License Portal",
    "app.digitalAdvertisementLicense": "Digital Advertisement License",
    "app.digitalAdvertisementLicenseSystem": "Digital Advertisement License System",
    "app.authFeatureSubmit": "Submit applications and documents online",
    "app.authFeatureTrack": "Track S2 verification, technical review, and approval",
    "app.authFeatureComplete": "Complete payment and receive QR e-license",
    "role.admin": "Administrator",
    "role.officer": "DBKU Officer",
    "role.applicant": "Applicant",
    "role.officerPortal": "Officer Portal",
    "role.applicantPortal": "Applicant Portal",
    "role.fasTrackUser": "fasTrack User",
    "nav.overview": "Overview",
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.myDashboard": "My Dashboard",
    "nav.applicationFlow": "Application Flow",
    "nav.applications": "Applications",
    "nav.myApplications": "My Applications",
    "nav.verification": "S2 Verification",
    "nav.technical": "Technical",
    "nav.approval": "Approval",
    "nav.payment": "Payment",
    "nav.license": "E-License / QR",
    "nav.enforcement": "Enforcement",
    "nav.reports": "Reports",
    "nav.notifications": "Notifications",
    "dashboard.eyebrow": "fasTrack System",
    "dashboard.title": "Advertisement License Dashboard",
    "dashboard.description":
      "Monitor digital advertisement license applications against the 25-day target: registration, verification, technical review, management recommendation, MPHLG, approval, payment, and e-license.",
    "dashboard.total": "Total Applications",
    "dashboard.totalNote": "All advertisement license applications",
    "dashboard.underReview": "Under Review",
    "dashboard.underReviewNote": "Waiting for licensing or technical action",
    "dashboard.pendingPayment": "Pending Payment",
    "dashboard.pendingPaymentNote": "Approved but payment not completed",
    "dashboard.licensesIssued": "Licenses Issued",
    "dashboard.licensesIssuedNote": "Active digital licenses",
    "dashboard.statusSummary": "Application Status Summary",
    "dashboard.statusSummaryDesc": "Total applications by flowchart phase.",
    "dashboard.sla": "SLA Monitoring",
    "dashboard.slaDesc": "The system-wide target is 25 days.",
    "dashboard.recent": "Recent Applications",
    "dashboard.recentDesc": "Advertisement license applications received or currently being processed.",
    "dashboard.flow": "System Flowchart",
    "dashboard.flowDesc": "Digital advertisement license process sequence based on the MPHLG chart.",
    "dashboard.departmentPerformance": "Department / Agency Performance",
    "dashboard.departmentDesc": "Monitor assigned, pending, and completed actions by role.",
    "auth.loginTitle": "Sign In",
    "auth.loginDescription": "Access your personal dashboard and services.",
    "auth.malaysian": "Malaysian",
    "auth.nonMalaysian": "Non-Malaysian",
    "auth.icNumber": "IC Number",
    "auth.emailAddress": "Email Address",
    "auth.password": "Password",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.enterIcPassword": "Please enter IC Number and password.",
    "auth.enterEmailPassword": "Please enter email and password.",
    "auth.loginIcFailed": "Login failed. Please check your IC Number and password.",
    "auth.loginEmailFailed": "Login failed. Please check your email and password.",
    "auth.registrationTitle": "Account Registration",
    "auth.registrationMalaysianDescription": "Complete the form below to create your account. Ensure all information matches your official identification documents.",
    "auth.registrationNonMalaysianDescription": "Complete the form below to create your account. Ensure all information matches your official passport documents.",
    "auth.personalInformation": "Personal Information",
    "auth.fullNameMyKadPassport": "Full Name (as per MyKad/Passport)",
    "auth.fullNamePassport": "Full Name (as per Passport)",
    "auth.fullNamePlaceholder": "Enter your full legal name",
    "auth.nationality": "Nationality",
    "auth.mykadNumber": "MyKad Number",
    "auth.enterWithoutDashes": "Enter without dashes",
    "auth.contactDetails": "Contact Details",
    "auth.mobileNumber": "Mobile Number",
    "auth.residentialAddress": "Residential Address",
    "auth.addressPlaceholder": "Enter your full correspondence address",
    "auth.accountSecurity": "Account Security",
    "auth.retypePassword": "Retype Password",
    "auth.secureWordHint": "The 'Secure Word' is used to verify the authenticity of the portal during login. Never enter your password if the secure word displayed does not match.",
    "auth.secureWord": "Secure Word",
    "auth.agreePrefix": "I have agreed to the",
    "auth.terms": "Terms and Conditions",
    "auth.privacy": "Privacy Policy",
    "auth.agreeSuffix": "governing the use of DBKU Portal.",
    "auth.submitRegistration": "Submit Registration",
    "auth.backToLogin": "Back to Login",
    "auth.passportNumber": "Passport Number",
    "auth.passportPlaceholder": "Enter your passport number",
    "auth.countryOfOrigin": "Country of Origin",
    "auth.selectCountry": "Select your country",
    "auth.passportExpiryDate": "Passport Expiry Date",
    "auth.copyright": "All Rights Reserved.",
    "auth.termsService": "Terms of Service",
    "auth.faq": "FAQ",
    "auth.contactUs": "Contact Us",
    "applicant.portal": "Applicant Portal",
    "applicant.records": "Applicant Records",
    "applicant.dashboardTitle": "My Advertisement License Applications",
    "applicant.dashboardDescription": "Start an online application, upload documents, track status in real time, receive decisions, complete payment, and download your QR e-license.",
    "applicant.applicationsTitle": "My Applications",
    "applicant.applicationsDescription": "Track every application from draft to S2 verification, technical review, approval, payment, and QR e-license.",
    "applicant.currentProgress": "Current Progress",
    "applicant.noApplicationSubmitted": "No application submitted yet.",
    "applicant.createApplicationHint": "Create a new application to start the registration phase.",
    "applicant.flowTitle": "Applicant (Front-End Module)",
    "applicant.flowDescription": "Complete applicant flow after login based on the digital advertisement license chart.",
    "applicant.startTitle": "Start",
    "applicant.startDesc": "Applicant enters the portal.",
    "applicant.s1Title": "Access Portal & Login",
    "applicant.s1Desc": "Applicant dashboard and active account.",
    "applicant.formUploadTitle": "Complete Form & Upload Documents",
    "applicant.formUploadDesc": "Complete 11 steps and supporting documents.",
    "applicant.statusCompleteTitle": "Status Complete?",
    "applicant.correctionEmailDesc": "Correction action through email.",
    "applicant.memoDesc": "If complete, an internal memo is generated.",
    "applicant.memoTitle": "Status 'Complete', Generate Internal Memo",
    "applicant.memoMoveDesc": "Application moves to the Licensing Division.",
    "applicant.decisionNoticeTitle": "Receive Decision Notification",
    "applicant.decisionNoticeDesc": "Notice of approved, conditional approval, or not approved.",
    "applicant.onlinePaymentTitle": "Make Online Payment",
    "applicant.onlinePaymentDesc": "FPX or card after invoice generation.",
    "applicant.licenseDownloadTitle": "Download E-License (QR Code)",
    "applicant.licenseDownloadDesc": "QR e-license can be downloaded after the license is issued.",
    "applicant.endTitle": "End",
    "applicant.endDesc": "Applicant flow completed.",
    "applicant.applicationSelected": "Application selected",
    "applicant.noApplicationYet": "No application yet",
    "applicant.startRequired": "Start required",
    "applicant.statusCorrection": "N: Correction",
    "applicant.statusCompleteYes": "Y: Complete",
    "applicant.actionsTitle": "Applicant Actions",
    "applicant.actionsDescription": "Complete the front-end applicant actions from application, correction, decision notification, payment, to QR e-license.",
    "applicant.actionsEmptyDescription": "Create a new application to activate applicant actions.",
    "applicant.s1ActionTitle": "Access portal, login, complete form, and upload documents",
    "applicant.actionRequired": "Action required",
    "applicant.completed": "Completed",
    "applicant.continueApplication": "Continue Application",
    "applicant.viewSubmission": "View Submission",
    "applicant.correctionTitle": "Receive correction notification and update incomplete information",
    "applicant.correctionRequired": "Correction required",
    "applicant.noCorrectionRequest": "No correction request",
    "applicant.emailCorrectionRequested": "Email correction requested",
    "applicant.noActiveCorrectionNotice": "No active correction notice",
    "applicant.updateApplicationForm": "Update the application form",
    "applicant.waitLicensingReview": "Wait for licensing review",
    "applicant.openCorrection": "Open Correction",
    "applicant.receiveDecisionTitle": "Receive decision notification from the approval stage",
    "applicant.paymentByFpxCard": "Online payment by FPX/card",
    "applicant.waitingInvoice": "Waiting for invoice",
    "applicant.notSubmitted": "Not submitted",
    "applicant.submitPayment": "Submit Payment",
    "applicant.selectedApplication": "Selected Application",
    "applicant.downloadQrELicense": "Download QR E-License",
    "applicant.qrLicensePending": "QR e-license will appear after payment has been verified and the license is issued.",
    "applicant.workflowInactive": "No applicant workflow is active yet.",
    "applicant.myApplicationsDesc": "A clean list of your draft and submitted records.",
    "applicant.noApplicationsYet": "No applications yet.",
    "applicant.searchPlaceholder": "Search reference, project, or type",
    "applicant.applicationList": "Application List",
    "applicant.recordsFound": "record(s) found.",
    "applicant.noUserApplications": "You have no applications yet.",
    "applicant.paymentSubmittedSuccess": "Payment submitted. DBKU will verify it before the QR e-license is issued.",
    "applicant.paymentSubmissionFailed": "Payment submission failed.",
    "applicant.detailsLoadFailed": "Unable to load selected application details.",
    "applicant.paymentHintDraft": "Complete and submit the application before payment is available.",
    "applicant.paymentHintRejected": "Payment is not available for rejected applications.",
    "applicant.paymentHintSubmitted": "Payment has been submitted and is waiting for DBKU verification.",
    "applicant.paymentHintVerified": "Payment has been verified. QR e-license issuance is next.",
    "applicant.paymentHintIssued": "Payment is complete and QR e-license is ready to download.",
    "applicant.paymentHintDefault": "Payment opens after approval and invoice generation.",
    "steps.applicationSteps": "Application Steps",
    "steps.stepOf": "Step {active} of {total}",
    "steps.editing": "Editing",
    "steps.saveFirstStepHint": "Save step 1 first to unlock the next steps.",
    "steps.sittingApplication": "Sitting Application",
    "steps.clientDepartment": "Details of Client Department",
    "steps.submittingPerson": "Details of Submitting Person",
    "steps.landDetails": "Details of Land(s)",
    "steps.buildingPlan": "Detailed Building Plan",
    "steps.proposalAnalysis": "Analysis of Proposal",
    "steps.siteInspection": "Site Inspection",
    "steps.buildingPlanChecklist": "Building Plan Checklist",
    "steps.printForm": "Print Form",
    "steps.supportingDocument": "Supporting Document",
    "steps.declaration": "Declaration",
    "decision.notApproved": "Not approved",
    "decision.approved": "Approved",
    "decision.waiting": "Waiting for decision",
    "decision.rejected": "Rejected",
    "decision.approvedWithConditions": "Approved with conditions",
    "decision.pending": "Pending",
    "decision.referNotice": "Please refer to DBKU notice",
    "decision.notificationReceived": "Decision notification received",
    "status.draft": "Draft",
    "status.incomplete": "Incomplete",
    "status.submitted": "Submitted",
    "status.auto_screened": "S2 Verification",
    "status.technical_review": "Technical Review",
    "status.technical_review_completed": "Technical Completed",
    "status.management_review": "Management Recommendation",
    "status.mphlg_processing": "MPHLG Processing",
    "status.mphlg_decision_received": "MPHLG Decision Received",
    "status.approved": "Approved",
    "status.approved_with_conditions": "Approved with Conditions",
    "status.rejected": "Rejected",
    "status.invoice_generated": "Invoice Generated",
    "status.payment_submitted": "Payment Submitted",
    "status.payment_verified": "Payment Verified",
    "status.license_issued": "E-License Generated",
    "status.license_revoked": "License Revoked",
  },
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
  if (typeof window === "undefined") return "ms";

  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "en" || stored === "ms" ? stored : "ms";
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(getInitialLanguage);

  useEffect(() => {
    document.documentElement.lang = language === "ms" ? "ms-MY" : "en";
  }, [language]);

  function setLanguage(nextLanguage) {
    const normalized = nextLanguage === "en" ? "en" : "ms";
    setLanguageState(normalized);
    localStorage.setItem(STORAGE_KEY, normalized);
    document.documentElement.lang = normalized === "ms" ? "ms-MY" : "en";
  }

  const value = useMemo(() => {
    function t(key, fallback) {
      return (
        dictionaries[language]?.[key] ||
        dictionaries.en[key] ||
        fallback ||
        key
      );
    }

    return {
      language,
      setLanguage,
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}
