# Generated by Django 5.2.13 on 2026-05-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_supportingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('auto_screened', 'S2 Verification'), ('technical_review', 'Technical Review'), ('technical_review_completed', 'Technical Review Completed'), ('management_review', 'Management Review'), ('mphlg_processing', 'MPHLG Processing'), ('mphlg_decision_received', 'MPHLG Decision Received'), ('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('rejected', 'Rejected'), ('invoice_generated', 'Invoice Generated'), ('payment_submitted', 'Payment Submitted'), ('payment_verified', 'Payment Verified'), ('license_issued', 'License Issued'), ('license_revoked', 'License Revoked')], default='draft', max_length=30),
        ),
    ]
