# Generated by Django 5.2.13 on 2026-05-12 00:44

from django.db import migrations, models


def populate_project_location(apps, schema_editor):
    Application = apps.get_model("applications", "Application")

    for application in Application.objects.all().iterator():
        form_data = application.form_data or {}
        step1 = form_data.get("step_1", {})
        step4 = form_data.get("step_4", {})
        project_location = (
            step1.get("locality_address")
            or step1.get("map_address")
            or step1.get("site_address")
            or step1.get("address")
            or step1.get("selected_address")
            or step4.get("land_location")
            or step4.get("location")
            or ""
        )

        if project_location:
            application.project_location = project_location[:500]
            application.save(update_fields=["project_location"])


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RunPython(
            populate_project_location,
            migrations.RunPython.noop,
        ),
    ]
