# Generated by Django 5.2.13 on 2026-05-12 03:35

from django.db import migrations, models


def get_latest_remark(form_data):
    form_data = form_data or {}

    def section(name):
        value = form_data.get(name) or {}
        return value if isinstance(value, dict) else {}

    candidates = [
        section("correction_request").get("remarks"),
        section("auto_screening").get("remarks"),
        section("technical_review").get("comment"),
        section("technical_review").get("remarks"),
        section("approval").get("notes"),
        section("approval").get("comment"),
        section("payment").get("verification_notes"),
    ]

    for value in candidates:
        value = str(value or "").strip()
        if value:
            return value

    return ""


def populate_latest_remark(apps, schema_editor):
    Application = apps.get_model("applications", "Application")

    for application in Application.objects.all().iterator():
        latest_remark = get_latest_remark(application.form_data)
        if latest_remark:
            application.latest_remark = latest_remark
            application.save(update_fields=["latest_remark"])


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='latest_remark',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(populate_latest_remark, migrations.RunPython.noop),
    ]
