# Generated by Django 5.2.13 on 2026-05-29 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_add_bill_pending_ku_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-updated_at'], name='app_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-updated_at'], name='app_applicant_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_type'], name='app_type_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-updated_at'], name='app_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['application', 'title'], name='doc_app_title_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['application', '-uploaded_at'], name='doc_app_uploaded_idx'),
        ),
    ]
